version: 2

project_name: qcloud

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/qcloud
    binary: qcloud
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
        -X main.version={{.Version}}
        -X main.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}"

changelog:
  disable: true

homebrew_casks:
  - name: qcloud
    binaries:
      - qcloud
    generate_completions_from_executable:
      shell_parameter_format: cobra
      shells:
        - bash
        - zsh
        - fish
    repository:
      owner: qdrant
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/qdrant/qcloud-cli
    description: The Command Line Interface for Qdrant Cloud
    license: Apache-2.0
    skip_upload: auto
