package space

import (
	"fmt"
	"io"
	"time"

	"github.com/spf13/cobra"

	spacev1 "github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/serverless/space/v1"

	"github.com/qdrant/qcloud-cli/internal/cmd/base"
	"github.com/qdrant/qcloud-cli/internal/state"
)

func newCreateCommand(s *state.State) *cobra.Command {
	return base.CreateCmd[*spacev1.Space]{
		Long: `Create a new serverless space in a cloud region.

The region is fixed for the lifetime of the space. When --name is omitted, a
unique, human-friendly name is generated by the server. Collection size limits
and search-worker settings default to the platform values and can be tightened
later with "qcloud serverless space update".

The space is provisioned asynchronously. Use --wait to block until it is ready
and its endpoint is available.`,
		Example: `# Create a space with a generated name
qcloud serverless space create --cloud-region eu-central-1

# Create a named space and wait until it is ready
qcloud serverless space create --cloud-region eu-central-1 --name my-space --wait

# Create a space restricted to an office network and a web app origin
qcloud serverless space create --cloud-region eu-central-1 --name my-space \
  --allowed-ip 203.0.113.0/24 --allowed-origin https://app.example.com

# Create a space with labels and per-collection limits
qcloud serverless space create --cloud-region eu-central-1 --name my-space \
  --label env=staging --max-collection-size 10GiB --searcher-max-workers 2`,
		BaseCobraCommand: func() *cobra.Command {
			cmd := &cobra.Command{
				Use:   "create",
				Short: "Create a new space",
				Args:  cobra.NoArgs,
			}
			cmd.Flags().String("cloud-region", "", "Cloud region ID to host the space in (required)")
			cmd.Flags().String("name", "", "Name of the space (default: generated by the server)")
			addSharedSpaceFlags(cmd)
			cmd.Flags().Bool("wait", false, "Wait for the space to become ready")
			cmd.Flags().Duration("wait-timeout", 10*time.Minute, "Maximum time to wait for the space to become ready")
			cmd.Flags().Duration("wait-poll-interval", 5*time.Second, "How often to poll the space status")
			_ = cmd.Flags().MarkHidden("wait-poll-interval")
			_ = cmd.MarkFlagRequired("cloud-region")
			return cmd
		},
		Run: func(s *state.State, cmd *cobra.Command, args []string) (*spacev1.Space, error) {
			ctx := cmd.Context()
			client, err := s.Client(ctx)
			if err != nil {
				return nil, err
			}

			accountID, err := s.AccountID()
			if err != nil {
				return nil, err
			}

			region, _ := cmd.Flags().GetString("cloud-region")
			name, _ := cmd.Flags().GetString("name")
			if name == "" {
				resp, err := client.ServerlessSpace().SuggestSpaceName(ctx, &spacev1.SuggestSpaceNameRequest{
					AccountId: accountID,
				})
				if err != nil {
					return nil, fmt.Errorf("failed to suggest a space name: %w", err)
				}

				name = resp.GetName()
			}

			space := &spacev1.Space{
				AccountId:     accountID,
				Name:          name,
				CloudRegionId: region,
			}
			if err := applySharedSpaceFlags(cmd, space); err != nil {
				return nil, err
			}

			resp, err := client.ServerlessSpace().CreateSpace(ctx, &spacev1.CreateSpaceRequest{Space: space})
			if err != nil {
				return nil, fmt.Errorf("failed to create space: %w", err)
			}

			created := resp.GetSpace()

			wait, _ := cmd.Flags().GetBool("wait")
			if !wait {
				return created, nil
			}

			waitTimeout, _ := cmd.Flags().GetDuration("wait-timeout")
			pollInterval, _ := cmd.Flags().GetDuration("wait-poll-interval")
			fmt.Fprintf(cmd.ErrOrStderr(), "Space %s created, waiting for it to become ready...\n", created.GetId())
			return waitForSpaceReady(ctx, client.ServerlessSpace(), cmd.ErrOrStderr(), accountID, created.GetId(), waitTimeout, pollInterval)
		},
		PrintResource: func(_ *cobra.Command, out io.Writer, created *spacev1.Space) {
			fmt.Fprint(out, spaceResultMessage(created, "created"))
		},
	}.CobraCommand(s)
}
