// Package framework provides shared helpers for the qcloud e2e test suite.
package framework

import (
	"archive/tar"
	"bufio"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"
)

const (
	envBinary  = "QCLOUD_E2E_BINARY"
	envRelease = "QCLOUD_E2E_RELEASE"

	releaseBaseURL = "https://github.com/qdrant/qcloud-cli/releases"
	defaultRelease = "latest"

	downloadTimeout = 2 * time.Minute
)

var (
	binaryOnce sync.Once
	binaryPath string
	binaryErr  error
)

// Binary returns the path to the qcloud binary to exercise. The binary is
// resolved exactly once per process:
//
//  1. $QCLOUD_E2E_BINARY, if set.
//  2. A cached download of the release named by $QCLOUD_E2E_RELEASE (default
//     "latest"), verified against the release's checksums.txt.
//
// Downloads are cached under os.UserCacheDir()/qcloud-e2e keyed by the archive
// sha256, so repeated test runs on the same host reuse the same binary.
func Binary() (string, error) {
	binaryOnce.Do(func() {
		binaryPath, binaryErr = resolveBinary()
	})
	return binaryPath, binaryErr
}

func resolveBinary() (string, error) {
	if p := os.Getenv(envBinary); p != "" {
		if _, err := os.Stat(p); err != nil {
			return "", fmt.Errorf("%s=%s: %w", envBinary, p, err)
		}
		return p, nil
	}

	release := os.Getenv(envRelease)
	if release == "" {
		release = defaultRelease
	}

	archive := fmt.Sprintf("qcloud-%s-%s.tar.gz", runtime.GOOS, runtime.GOARCH)
	base := fmt.Sprintf("%s/%s/download", releaseBaseURL, release)

	expectedSHA, err := fetchExpectedSHA(base+"/checksums.txt", archive)
	if err != nil {
		return "", err
	}

	cacheDir, err := binaryCacheDir(expectedSHA)
	if err != nil {
		return "", err
	}

	binary := filepath.Join(cacheDir, "qcloud")
	if _, err := os.Stat(binary); err == nil {
		return binary, nil
	}

	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		return "", fmt.Errorf("creating cache dir: %w", err)
	}

	tmp, err := downloadVerified(base+"/"+archive, expectedSHA)
	if err != nil {
		return "", err
	}
	defer func() { _ = os.Remove(tmp) }()

	if err := extractQcloud(tmp, binary); err != nil {
		return "", err
	}
	if err := os.Chmod(binary, 0o755); err != nil {
		return "", fmt.Errorf("chmod binary: %w", err)
	}
	return binary, nil
}

func binaryCacheDir(sha string) (string, error) {
	root, err := os.UserCacheDir()
	if err != nil {
		return "", fmt.Errorf("resolving user cache dir: %w", err)
	}
	return filepath.Join(root, "qcloud-e2e", sha[:16]), nil
}

// fetchExpectedSHA downloads checksums.txt and returns the sha256 for the
// given archive file name. The file is generated by goreleaser and looks like:
//
//	a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2  qcloud-linux-amd64.tar.gz
//	f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5  qcloud-linux-arm64.tar.gz
//	9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b  qcloud-darwin-arm64.tar.gz
func fetchExpectedSHA(url, archive string) (string, error) {
	body, err := httpGetBody(url)
	if err != nil {
		return "", err
	}
	defer func() { _ = body.Close() }()

	scan := bufio.NewScanner(body)
	for scan.Scan() {
		fields := strings.Fields(scan.Text())
		if len(fields) != 2 {
			continue
		}
		if fields[1] == archive {
			return fields[0], nil
		}
	}
	if err := scan.Err(); err != nil {
		return "", fmt.Errorf("reading checksums: %w", err)
	}
	return "", fmt.Errorf("%s not listed in %s", archive, url)
}

// downloadVerified writes the URL body to a temp file and verifies the
// sha256 against expected. Returns the temp file path on success.
func downloadVerified(url, expected string) (string, error) {
	body, err := httpGetBody(url)
	if err != nil {
		return "", err
	}
	defer func() { _ = body.Close() }()

	tmp, err := os.CreateTemp("", "qcloud-e2e-*.tar.gz")
	if err != nil {
		return "", fmt.Errorf("creating temp archive: %w", err)
	}
	defer func() { _ = tmp.Close() }()

	h := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tmp, h), body); err != nil {
		_ = os.Remove(tmp.Name())
		return "", fmt.Errorf("downloading %s: %w", url, err)
	}

	got := hex.EncodeToString(h.Sum(nil))
	if got != expected {
		_ = os.Remove(tmp.Name())
		return "", fmt.Errorf("checksum mismatch for %s: got %s, want %s", url, got, expected)
	}
	return tmp.Name(), nil
}

func httpGetBody(url string) (io.ReadCloser, error) {
	client := &http.Client{Timeout: downloadTimeout}
	resp, err := client.Get(url) //nolint:noctx // bounded by client timeout
	if err != nil {
		return nil, fmt.Errorf("GET %s: %w", url, err)
	}
	if resp.StatusCode != http.StatusOK {
		_ = resp.Body.Close()
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return resp.Body, nil
}

// extractQcloud pulls the "qcloud" binary out of a gzip-compressed tar at
// src and writes it to dst.
func extractQcloud(src, dst string) error {
	f, err := os.Open(src)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	gr, err := gzip.NewReader(f)
	if err != nil {
		return fmt.Errorf("gzip reader: %w", err)
	}
	defer func() { _ = gr.Close() }()

	tr := tar.NewReader(gr)
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return fmt.Errorf("qcloud binary not found in %s", src)
		}
		if err != nil {
			return fmt.Errorf("tar reader: %w", err)
		}
		if filepath.Base(hdr.Name) != "qcloud" {
			continue
		}

		out, err := os.Create(dst)
		if err != nil {
			return err
		}
		if _, err := io.Copy(out, tr); err != nil {
			_ = out.Close()
			return err
		}
		return out.Close()
	}
}
