package cluster_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	bookingv1 "github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/booking/v1"
	clusterv1 "github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/cluster/v1"
	platformv1 "github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/platform/v1"

	"github.com/qdrant/qcloud-cli/internal/testutil"
)

// Completion tests invoke the binary with "__complete" as the subcommand.
// This is not a shell convention — it is a Cobra internal: the shell completion
// script generated by "qcloud completion <shell>" calls "__complete <args...>"
// to ask the binary for candidates. Invoking it directly here lets us test
// completion logic without a real shell.
func TestClusterIDCompletion(t *testing.T) {
	env := testutil.NewTestEnv(t)

	env.Server.ListClustersCalls.Returns(&clusterv1.ListClustersResponse{
		Items: []*clusterv1.Cluster{
			{Id: "cluster-abc", Name: "my-cluster"},
			{Id: "cluster-xyz", Name: "other-cluster"},
		},
	}, nil)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "describe", "")
	require.NoError(t, err)
	assert.Contains(t, stdout, "cluster-abc")
	assert.Contains(t, stdout, "my-cluster")
	assert.Contains(t, stdout, "cluster-xyz")
}

func TestCloudProviderCompletion(t *testing.T) {
	env := testutil.NewTestEnv(t)

	env.PlatformServer.ListCloudProvidersCalls.Returns(&platformv1.ListCloudProvidersResponse{
		Items: []*platformv1.CloudProvider{
			{Id: "aws", Name: "Amazon Web Services"},
			{Id: "gcp", Name: "Google Cloud"},
		},
	}, nil)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "list", "--cloud-provider", "")
	require.NoError(t, err)
	assert.Contains(t, stdout, "aws")
	assert.Contains(t, stdout, "Amazon Web Services")
	assert.Contains(t, stdout, "gcp")
}

func TestCloudRegionCompletion(t *testing.T) {
	env := testutil.NewTestEnv(t)

	env.PlatformServer.ListCloudProviderRegionsCalls.Returns(&platformv1.ListCloudProviderRegionsResponse{
		Items: []*platformv1.CloudProviderRegion{
			{Id: "us-east-1", Name: "US East (N. Virginia)"},
		},
	}, nil)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "list", "--cloud-provider", "aws", "--cloud-region", "")
	require.NoError(t, err)
	assert.Contains(t, stdout, "us-east-1")
	assert.Contains(t, stdout, "US East")
}

func TestCloudRegionCompletion_NoProvider(t *testing.T) {
	env := testutil.NewTestEnv(t)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "list", "--cloud-region", "")
	require.NoError(t, err)
	// No completions when provider is not set.
	assert.NotContains(t, stdout, "us-east-1")
}

func TestPackageCompletion(t *testing.T) {
	env := testutil.NewTestEnv(t)

	env.BookingServer.ListPackagesCalls.Returns(&bookingv1.ListPackagesResponse{
		Items: []*bookingv1.Package{
			{Id: "pkg-uuid-1", Name: "startup-4"},
			{Id: "pkg-uuid-2", Name: "business-8"},
		},
	}, nil)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "create", "--cloud-provider", "aws", "--cloud-region", "us-east-1", "--package", "")
	require.NoError(t, err)
	assert.Contains(t, stdout, "startup-4")
	assert.Contains(t, stdout, "business-8")
}

func TestPackageCompletion_NoProvider(t *testing.T) {
	env := testutil.NewTestEnv(t)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "create", "--package", "")
	require.NoError(t, err)
	assert.NotContains(t, stdout, "startup-4")
}

func TestVersionCompletion(t *testing.T) {
	env := testutil.NewTestEnv(t)

	remarks := "upgrade recommended"
	env.Server.ListQdrantReleasesCalls.Returns(&clusterv1.ListQdrantReleasesResponse{
		Items: []*clusterv1.QdrantRelease{
			{Version: "1.14.0", Default: true},
			{Version: "1.13.0", EndOfLife: true},
			{Version: "1.12.0", Unavailable: true},
			{Version: "1.11.0", Remarks: &remarks},
		},
	}, nil)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "create", "--cloud-provider", "aws", "--cloud-region", "us-east-1", "--version", "")
	require.NoError(t, err)
	assert.Contains(t, stdout, "1.14.0")
	assert.Contains(t, stdout, "(default)")
	assert.Contains(t, stdout, "1.13.0")
	assert.Contains(t, stdout, "(end of life)")
	assert.Contains(t, stdout, "1.11.0")
	assert.Contains(t, stdout, "upgrade recommended")
	assert.NotContains(t, stdout, "1.12.0")
}

func TestVersionCompletion_UnavailableExcluded(t *testing.T) {
	env := testutil.NewTestEnv(t)

	env.Server.ListQdrantReleasesCalls.Returns(&clusterv1.ListQdrantReleasesResponse{
		Items: []*clusterv1.QdrantRelease{
			{Version: "1.14.0"},
			{Version: "1.13.0", Unavailable: true},
		},
	}, nil)

	stdout, _, err := testutil.Exec(t, env, "__complete", "cluster", "create", "--cloud-provider", "aws", "--cloud-region", "us-east-1", "--version", "")
	require.NoError(t, err)
	assert.Contains(t, stdout, "1.14.0")
	assert.NotContains(t, stdout, "1.13.0")
}
