// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/qdrant/qcloud-cli/internal/selfupgrade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// DetectLatest provides a mock function for the type MockUpdater
func (_mock *MockUpdater) DetectLatest(ctx context.Context) (*selfupgrade.ReleaseInfo, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DetectLatest")
	}

	var r0 *selfupgrade.ReleaseInfo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*selfupgrade.ReleaseInfo, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *selfupgrade.ReleaseInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*selfupgrade.ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUpdater_DetectLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectLatest'
type MockUpdater_DetectLatest_Call struct {
	*mock.Call
}

// DetectLatest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdater_Expecter) DetectLatest(ctx interface{}) *MockUpdater_DetectLatest_Call {
	return &MockUpdater_DetectLatest_Call{Call: _e.mock.On("DetectLatest", ctx)}
}

func (_c *MockUpdater_DetectLatest_Call) Run(run func(ctx context.Context)) *MockUpdater_DetectLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdater_DetectLatest_Call) Return(releaseInfo *selfupgrade.ReleaseInfo, b bool, err error) *MockUpdater_DetectLatest_Call {
	_c.Call.Return(releaseInfo, b, err)
	return _c
}

func (_c *MockUpdater_DetectLatest_Call) RunAndReturn(run func(ctx context.Context) (*selfupgrade.ReleaseInfo, bool, error)) *MockUpdater_DetectLatest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSelf provides a mock function for the type MockUpdater
func (_mock *MockUpdater) UpdateSelf(ctx context.Context, currentVersion string) (*selfupgrade.ReleaseInfo, error) {
	ret := _mock.Called(ctx, currentVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSelf")
	}

	var r0 *selfupgrade.ReleaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*selfupgrade.ReleaseInfo, error)); ok {
		return returnFunc(ctx, currentVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *selfupgrade.ReleaseInfo); ok {
		r0 = returnFunc(ctx, currentVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*selfupgrade.ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, currentVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdater_UpdateSelf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSelf'
type MockUpdater_UpdateSelf_Call struct {
	*mock.Call
}

// UpdateSelf is a helper method to define mock.On call
//   - ctx context.Context
//   - currentVersion string
func (_e *MockUpdater_Expecter) UpdateSelf(ctx interface{}, currentVersion interface{}) *MockUpdater_UpdateSelf_Call {
	return &MockUpdater_UpdateSelf_Call{Call: _e.mock.On("UpdateSelf", ctx, currentVersion)}
}

func (_c *MockUpdater_UpdateSelf_Call) Run(run func(ctx context.Context, currentVersion string)) *MockUpdater_UpdateSelf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdater_UpdateSelf_Call) Return(releaseInfo *selfupgrade.ReleaseInfo, err error) *MockUpdater_UpdateSelf_Call {
	_c.Call.Return(releaseInfo, err)
	return _c
}

func (_c *MockUpdater_UpdateSelf_Call) RunAndReturn(run func(ctx context.Context, currentVersion string) (*selfupgrade.ReleaseInfo, error)) *MockUpdater_UpdateSelf_Call {
	_c.Call.Return(run)
	return _c
}
