// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/cluster/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClusterServiceServer creates a new instance of MockClusterServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterServiceServer {
	mock := &MockClusterServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClusterServiceServer is an autogenerated mock type for the ClusterServiceServer type
type MockClusterServiceServer struct {
	mock.Mock
}

type MockClusterServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterServiceServer) EXPECT() *MockClusterServiceServer_Expecter {
	return &MockClusterServiceServer_Expecter{mock: &_m.Mock}
}

// CreateCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) CreateCluster(context1 context.Context, createClusterRequest *clusterv1.CreateClusterRequest) (*clusterv1.CreateClusterResponse, error) {
	ret := _mock.Called(context1, createClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 *clusterv1.CreateClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.CreateClusterRequest) (*clusterv1.CreateClusterResponse, error)); ok {
		return returnFunc(context1, createClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.CreateClusterRequest) *clusterv1.CreateClusterResponse); ok {
		r0 = returnFunc(context1, createClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.CreateClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.CreateClusterRequest) error); ok {
		r1 = returnFunc(context1, createClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type MockClusterServiceServer_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - createClusterRequest *clusterv1.CreateClusterRequest
func (_e *MockClusterServiceServer_Expecter) CreateCluster(context1 interface{}, createClusterRequest interface{}) *MockClusterServiceServer_CreateCluster_Call {
	return &MockClusterServiceServer_CreateCluster_Call{Call: _e.mock.On("CreateCluster", context1, createClusterRequest)}
}

func (_c *MockClusterServiceServer_CreateCluster_Call) Run(run func(context1 context.Context, createClusterRequest *clusterv1.CreateClusterRequest)) *MockClusterServiceServer_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.CreateClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.CreateClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_CreateCluster_Call) Return(createClusterResponse *clusterv1.CreateClusterResponse, err error) *MockClusterServiceServer_CreateCluster_Call {
	_c.Call.Return(createClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_CreateCluster_Call) RunAndReturn(run func(context1 context.Context, createClusterRequest *clusterv1.CreateClusterRequest) (*clusterv1.CreateClusterResponse, error)) *MockClusterServiceServer_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClusterFromBackup provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) CreateClusterFromBackup(context1 context.Context, createClusterFromBackupRequest *clusterv1.CreateClusterFromBackupRequest) (*clusterv1.CreateClusterFromBackupResponse, error) {
	ret := _mock.Called(context1, createClusterFromBackupRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterFromBackup")
	}

	var r0 *clusterv1.CreateClusterFromBackupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.CreateClusterFromBackupRequest) (*clusterv1.CreateClusterFromBackupResponse, error)); ok {
		return returnFunc(context1, createClusterFromBackupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.CreateClusterFromBackupRequest) *clusterv1.CreateClusterFromBackupResponse); ok {
		r0 = returnFunc(context1, createClusterFromBackupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.CreateClusterFromBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.CreateClusterFromBackupRequest) error); ok {
		r1 = returnFunc(context1, createClusterFromBackupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_CreateClusterFromBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterFromBackup'
type MockClusterServiceServer_CreateClusterFromBackup_Call struct {
	*mock.Call
}

// CreateClusterFromBackup is a helper method to define mock.On call
//   - context1 context.Context
//   - createClusterFromBackupRequest *clusterv1.CreateClusterFromBackupRequest
func (_e *MockClusterServiceServer_Expecter) CreateClusterFromBackup(context1 interface{}, createClusterFromBackupRequest interface{}) *MockClusterServiceServer_CreateClusterFromBackup_Call {
	return &MockClusterServiceServer_CreateClusterFromBackup_Call{Call: _e.mock.On("CreateClusterFromBackup", context1, createClusterFromBackupRequest)}
}

func (_c *MockClusterServiceServer_CreateClusterFromBackup_Call) Run(run func(context1 context.Context, createClusterFromBackupRequest *clusterv1.CreateClusterFromBackupRequest)) *MockClusterServiceServer_CreateClusterFromBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.CreateClusterFromBackupRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.CreateClusterFromBackupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_CreateClusterFromBackup_Call) Return(createClusterFromBackupResponse *clusterv1.CreateClusterFromBackupResponse, err error) *MockClusterServiceServer_CreateClusterFromBackup_Call {
	_c.Call.Return(createClusterFromBackupResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_CreateClusterFromBackup_Call) RunAndReturn(run func(context1 context.Context, createClusterFromBackupRequest *clusterv1.CreateClusterFromBackupRequest) (*clusterv1.CreateClusterFromBackupResponse, error)) *MockClusterServiceServer_CreateClusterFromBackup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) DeleteCluster(context1 context.Context, deleteClusterRequest *clusterv1.DeleteClusterRequest) (*clusterv1.DeleteClusterResponse, error) {
	ret := _mock.Called(context1, deleteClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 *clusterv1.DeleteClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.DeleteClusterRequest) (*clusterv1.DeleteClusterResponse, error)); ok {
		return returnFunc(context1, deleteClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.DeleteClusterRequest) *clusterv1.DeleteClusterResponse); ok {
		r0 = returnFunc(context1, deleteClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.DeleteClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.DeleteClusterRequest) error); ok {
		r1 = returnFunc(context1, deleteClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type MockClusterServiceServer_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteClusterRequest *clusterv1.DeleteClusterRequest
func (_e *MockClusterServiceServer_Expecter) DeleteCluster(context1 interface{}, deleteClusterRequest interface{}) *MockClusterServiceServer_DeleteCluster_Call {
	return &MockClusterServiceServer_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", context1, deleteClusterRequest)}
}

func (_c *MockClusterServiceServer_DeleteCluster_Call) Run(run func(context1 context.Context, deleteClusterRequest *clusterv1.DeleteClusterRequest)) *MockClusterServiceServer_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.DeleteClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.DeleteClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_DeleteCluster_Call) Return(deleteClusterResponse *clusterv1.DeleteClusterResponse, err error) *MockClusterServiceServer_DeleteCluster_Call {
	_c.Call.Return(deleteClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_DeleteCluster_Call) RunAndReturn(run func(context1 context.Context, deleteClusterRequest *clusterv1.DeleteClusterRequest) (*clusterv1.DeleteClusterResponse, error)) *MockClusterServiceServer_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// EnableClusterJwtRbac provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) EnableClusterJwtRbac(context1 context.Context, enableClusterJwtRbacRequest *clusterv1.EnableClusterJwtRbacRequest) (*clusterv1.EnableClusterJwtRbacResponse, error) {
	ret := _mock.Called(context1, enableClusterJwtRbacRequest)

	if len(ret) == 0 {
		panic("no return value specified for EnableClusterJwtRbac")
	}

	var r0 *clusterv1.EnableClusterJwtRbacResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.EnableClusterJwtRbacRequest) (*clusterv1.EnableClusterJwtRbacResponse, error)); ok {
		return returnFunc(context1, enableClusterJwtRbacRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.EnableClusterJwtRbacRequest) *clusterv1.EnableClusterJwtRbacResponse); ok {
		r0 = returnFunc(context1, enableClusterJwtRbacRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.EnableClusterJwtRbacResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.EnableClusterJwtRbacRequest) error); ok {
		r1 = returnFunc(context1, enableClusterJwtRbacRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_EnableClusterJwtRbac_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableClusterJwtRbac'
type MockClusterServiceServer_EnableClusterJwtRbac_Call struct {
	*mock.Call
}

// EnableClusterJwtRbac is a helper method to define mock.On call
//   - context1 context.Context
//   - enableClusterJwtRbacRequest *clusterv1.EnableClusterJwtRbacRequest
func (_e *MockClusterServiceServer_Expecter) EnableClusterJwtRbac(context1 interface{}, enableClusterJwtRbacRequest interface{}) *MockClusterServiceServer_EnableClusterJwtRbac_Call {
	return &MockClusterServiceServer_EnableClusterJwtRbac_Call{Call: _e.mock.On("EnableClusterJwtRbac", context1, enableClusterJwtRbacRequest)}
}

func (_c *MockClusterServiceServer_EnableClusterJwtRbac_Call) Run(run func(context1 context.Context, enableClusterJwtRbacRequest *clusterv1.EnableClusterJwtRbacRequest)) *MockClusterServiceServer_EnableClusterJwtRbac_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.EnableClusterJwtRbacRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.EnableClusterJwtRbacRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_EnableClusterJwtRbac_Call) Return(enableClusterJwtRbacResponse *clusterv1.EnableClusterJwtRbacResponse, err error) *MockClusterServiceServer_EnableClusterJwtRbac_Call {
	_c.Call.Return(enableClusterJwtRbacResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_EnableClusterJwtRbac_Call) RunAndReturn(run func(context1 context.Context, enableClusterJwtRbacRequest *clusterv1.EnableClusterJwtRbacRequest) (*clusterv1.EnableClusterJwtRbacResponse, error)) *MockClusterServiceServer_EnableClusterJwtRbac_Call {
	_c.Call.Return(run)
	return _c
}

// GetCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) GetCluster(context1 context.Context, getClusterRequest *clusterv1.GetClusterRequest) (*clusterv1.GetClusterResponse, error) {
	ret := _mock.Called(context1, getClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *clusterv1.GetClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.GetClusterRequest) (*clusterv1.GetClusterResponse, error)); ok {
		return returnFunc(context1, getClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.GetClusterRequest) *clusterv1.GetClusterResponse); ok {
		r0 = returnFunc(context1, getClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.GetClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.GetClusterRequest) error); ok {
		r1 = returnFunc(context1, getClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type MockClusterServiceServer_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - getClusterRequest *clusterv1.GetClusterRequest
func (_e *MockClusterServiceServer_Expecter) GetCluster(context1 interface{}, getClusterRequest interface{}) *MockClusterServiceServer_GetCluster_Call {
	return &MockClusterServiceServer_GetCluster_Call{Call: _e.mock.On("GetCluster", context1, getClusterRequest)}
}

func (_c *MockClusterServiceServer_GetCluster_Call) Run(run func(context1 context.Context, getClusterRequest *clusterv1.GetClusterRequest)) *MockClusterServiceServer_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.GetClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.GetClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_GetCluster_Call) Return(getClusterResponse *clusterv1.GetClusterResponse, err error) *MockClusterServiceServer_GetCluster_Call {
	_c.Call.Return(getClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_GetCluster_Call) RunAndReturn(run func(context1 context.Context, getClusterRequest *clusterv1.GetClusterRequest) (*clusterv1.GetClusterResponse, error)) *MockClusterServiceServer_GetCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetQdrantRelease provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) GetQdrantRelease(context1 context.Context, getQdrantReleaseRequest *clusterv1.GetQdrantReleaseRequest) (*clusterv1.GetQdrantReleaseResponse, error) {
	ret := _mock.Called(context1, getQdrantReleaseRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetQdrantRelease")
	}

	var r0 *clusterv1.GetQdrantReleaseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.GetQdrantReleaseRequest) (*clusterv1.GetQdrantReleaseResponse, error)); ok {
		return returnFunc(context1, getQdrantReleaseRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.GetQdrantReleaseRequest) *clusterv1.GetQdrantReleaseResponse); ok {
		r0 = returnFunc(context1, getQdrantReleaseRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.GetQdrantReleaseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.GetQdrantReleaseRequest) error); ok {
		r1 = returnFunc(context1, getQdrantReleaseRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_GetQdrantRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQdrantRelease'
type MockClusterServiceServer_GetQdrantRelease_Call struct {
	*mock.Call
}

// GetQdrantRelease is a helper method to define mock.On call
//   - context1 context.Context
//   - getQdrantReleaseRequest *clusterv1.GetQdrantReleaseRequest
func (_e *MockClusterServiceServer_Expecter) GetQdrantRelease(context1 interface{}, getQdrantReleaseRequest interface{}) *MockClusterServiceServer_GetQdrantRelease_Call {
	return &MockClusterServiceServer_GetQdrantRelease_Call{Call: _e.mock.On("GetQdrantRelease", context1, getQdrantReleaseRequest)}
}

func (_c *MockClusterServiceServer_GetQdrantRelease_Call) Run(run func(context1 context.Context, getQdrantReleaseRequest *clusterv1.GetQdrantReleaseRequest)) *MockClusterServiceServer_GetQdrantRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.GetQdrantReleaseRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.GetQdrantReleaseRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_GetQdrantRelease_Call) Return(getQdrantReleaseResponse *clusterv1.GetQdrantReleaseResponse, err error) *MockClusterServiceServer_GetQdrantRelease_Call {
	_c.Call.Return(getQdrantReleaseResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_GetQdrantRelease_Call) RunAndReturn(run func(context1 context.Context, getQdrantReleaseRequest *clusterv1.GetQdrantReleaseRequest) (*clusterv1.GetQdrantReleaseResponse, error)) *MockClusterServiceServer_GetQdrantRelease_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) ListClusters(context1 context.Context, listClustersRequest *clusterv1.ListClustersRequest) (*clusterv1.ListClustersResponse, error) {
	ret := _mock.Called(context1, listClustersRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 *clusterv1.ListClustersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.ListClustersRequest) (*clusterv1.ListClustersResponse, error)); ok {
		return returnFunc(context1, listClustersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.ListClustersRequest) *clusterv1.ListClustersResponse); ok {
		r0 = returnFunc(context1, listClustersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.ListClustersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.ListClustersRequest) error); ok {
		r1 = returnFunc(context1, listClustersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type MockClusterServiceServer_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - context1 context.Context
//   - listClustersRequest *clusterv1.ListClustersRequest
func (_e *MockClusterServiceServer_Expecter) ListClusters(context1 interface{}, listClustersRequest interface{}) *MockClusterServiceServer_ListClusters_Call {
	return &MockClusterServiceServer_ListClusters_Call{Call: _e.mock.On("ListClusters", context1, listClustersRequest)}
}

func (_c *MockClusterServiceServer_ListClusters_Call) Run(run func(context1 context.Context, listClustersRequest *clusterv1.ListClustersRequest)) *MockClusterServiceServer_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.ListClustersRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.ListClustersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_ListClusters_Call) Return(listClustersResponse *clusterv1.ListClustersResponse, err error) *MockClusterServiceServer_ListClusters_Call {
	_c.Call.Return(listClustersResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_ListClusters_Call) RunAndReturn(run func(context1 context.Context, listClustersRequest *clusterv1.ListClustersRequest) (*clusterv1.ListClustersResponse, error)) *MockClusterServiceServer_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// ListQdrantReleases provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) ListQdrantReleases(context1 context.Context, listQdrantReleasesRequest *clusterv1.ListQdrantReleasesRequest) (*clusterv1.ListQdrantReleasesResponse, error) {
	ret := _mock.Called(context1, listQdrantReleasesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListQdrantReleases")
	}

	var r0 *clusterv1.ListQdrantReleasesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.ListQdrantReleasesRequest) (*clusterv1.ListQdrantReleasesResponse, error)); ok {
		return returnFunc(context1, listQdrantReleasesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.ListQdrantReleasesRequest) *clusterv1.ListQdrantReleasesResponse); ok {
		r0 = returnFunc(context1, listQdrantReleasesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.ListQdrantReleasesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.ListQdrantReleasesRequest) error); ok {
		r1 = returnFunc(context1, listQdrantReleasesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_ListQdrantReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQdrantReleases'
type MockClusterServiceServer_ListQdrantReleases_Call struct {
	*mock.Call
}

// ListQdrantReleases is a helper method to define mock.On call
//   - context1 context.Context
//   - listQdrantReleasesRequest *clusterv1.ListQdrantReleasesRequest
func (_e *MockClusterServiceServer_Expecter) ListQdrantReleases(context1 interface{}, listQdrantReleasesRequest interface{}) *MockClusterServiceServer_ListQdrantReleases_Call {
	return &MockClusterServiceServer_ListQdrantReleases_Call{Call: _e.mock.On("ListQdrantReleases", context1, listQdrantReleasesRequest)}
}

func (_c *MockClusterServiceServer_ListQdrantReleases_Call) Run(run func(context1 context.Context, listQdrantReleasesRequest *clusterv1.ListQdrantReleasesRequest)) *MockClusterServiceServer_ListQdrantReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.ListQdrantReleasesRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.ListQdrantReleasesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_ListQdrantReleases_Call) Return(listQdrantReleasesResponse *clusterv1.ListQdrantReleasesResponse, err error) *MockClusterServiceServer_ListQdrantReleases_Call {
	_c.Call.Return(listQdrantReleasesResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_ListQdrantReleases_Call) RunAndReturn(run func(context1 context.Context, listQdrantReleasesRequest *clusterv1.ListQdrantReleasesRequest) (*clusterv1.ListQdrantReleasesResponse, error)) *MockClusterServiceServer_ListQdrantReleases_Call {
	_c.Call.Return(run)
	return _c
}

// RestartCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) RestartCluster(context1 context.Context, restartClusterRequest *clusterv1.RestartClusterRequest) (*clusterv1.RestartClusterResponse, error) {
	ret := _mock.Called(context1, restartClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for RestartCluster")
	}

	var r0 *clusterv1.RestartClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.RestartClusterRequest) (*clusterv1.RestartClusterResponse, error)); ok {
		return returnFunc(context1, restartClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.RestartClusterRequest) *clusterv1.RestartClusterResponse); ok {
		r0 = returnFunc(context1, restartClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.RestartClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.RestartClusterRequest) error); ok {
		r1 = returnFunc(context1, restartClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_RestartCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartCluster'
type MockClusterServiceServer_RestartCluster_Call struct {
	*mock.Call
}

// RestartCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - restartClusterRequest *clusterv1.RestartClusterRequest
func (_e *MockClusterServiceServer_Expecter) RestartCluster(context1 interface{}, restartClusterRequest interface{}) *MockClusterServiceServer_RestartCluster_Call {
	return &MockClusterServiceServer_RestartCluster_Call{Call: _e.mock.On("RestartCluster", context1, restartClusterRequest)}
}

func (_c *MockClusterServiceServer_RestartCluster_Call) Run(run func(context1 context.Context, restartClusterRequest *clusterv1.RestartClusterRequest)) *MockClusterServiceServer_RestartCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.RestartClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.RestartClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_RestartCluster_Call) Return(restartClusterResponse *clusterv1.RestartClusterResponse, err error) *MockClusterServiceServer_RestartCluster_Call {
	_c.Call.Return(restartClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_RestartCluster_Call) RunAndReturn(run func(context1 context.Context, restartClusterRequest *clusterv1.RestartClusterRequest) (*clusterv1.RestartClusterResponse, error)) *MockClusterServiceServer_RestartCluster_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestClusterName provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) SuggestClusterName(context1 context.Context, suggestClusterNameRequest *clusterv1.SuggestClusterNameRequest) (*clusterv1.SuggestClusterNameResponse, error) {
	ret := _mock.Called(context1, suggestClusterNameRequest)

	if len(ret) == 0 {
		panic("no return value specified for SuggestClusterName")
	}

	var r0 *clusterv1.SuggestClusterNameResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.SuggestClusterNameRequest) (*clusterv1.SuggestClusterNameResponse, error)); ok {
		return returnFunc(context1, suggestClusterNameRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.SuggestClusterNameRequest) *clusterv1.SuggestClusterNameResponse); ok {
		r0 = returnFunc(context1, suggestClusterNameRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.SuggestClusterNameResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.SuggestClusterNameRequest) error); ok {
		r1 = returnFunc(context1, suggestClusterNameRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_SuggestClusterName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestClusterName'
type MockClusterServiceServer_SuggestClusterName_Call struct {
	*mock.Call
}

// SuggestClusterName is a helper method to define mock.On call
//   - context1 context.Context
//   - suggestClusterNameRequest *clusterv1.SuggestClusterNameRequest
func (_e *MockClusterServiceServer_Expecter) SuggestClusterName(context1 interface{}, suggestClusterNameRequest interface{}) *MockClusterServiceServer_SuggestClusterName_Call {
	return &MockClusterServiceServer_SuggestClusterName_Call{Call: _e.mock.On("SuggestClusterName", context1, suggestClusterNameRequest)}
}

func (_c *MockClusterServiceServer_SuggestClusterName_Call) Run(run func(context1 context.Context, suggestClusterNameRequest *clusterv1.SuggestClusterNameRequest)) *MockClusterServiceServer_SuggestClusterName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.SuggestClusterNameRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.SuggestClusterNameRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_SuggestClusterName_Call) Return(suggestClusterNameResponse *clusterv1.SuggestClusterNameResponse, err error) *MockClusterServiceServer_SuggestClusterName_Call {
	_c.Call.Return(suggestClusterNameResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_SuggestClusterName_Call) RunAndReturn(run func(context1 context.Context, suggestClusterNameRequest *clusterv1.SuggestClusterNameRequest) (*clusterv1.SuggestClusterNameResponse, error)) *MockClusterServiceServer_SuggestClusterName_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) SuspendCluster(context1 context.Context, suspendClusterRequest *clusterv1.SuspendClusterRequest) (*clusterv1.SuspendClusterResponse, error) {
	ret := _mock.Called(context1, suspendClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for SuspendCluster")
	}

	var r0 *clusterv1.SuspendClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.SuspendClusterRequest) (*clusterv1.SuspendClusterResponse, error)); ok {
		return returnFunc(context1, suspendClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.SuspendClusterRequest) *clusterv1.SuspendClusterResponse); ok {
		r0 = returnFunc(context1, suspendClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.SuspendClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.SuspendClusterRequest) error); ok {
		r1 = returnFunc(context1, suspendClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_SuspendCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendCluster'
type MockClusterServiceServer_SuspendCluster_Call struct {
	*mock.Call
}

// SuspendCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - suspendClusterRequest *clusterv1.SuspendClusterRequest
func (_e *MockClusterServiceServer_Expecter) SuspendCluster(context1 interface{}, suspendClusterRequest interface{}) *MockClusterServiceServer_SuspendCluster_Call {
	return &MockClusterServiceServer_SuspendCluster_Call{Call: _e.mock.On("SuspendCluster", context1, suspendClusterRequest)}
}

func (_c *MockClusterServiceServer_SuspendCluster_Call) Run(run func(context1 context.Context, suspendClusterRequest *clusterv1.SuspendClusterRequest)) *MockClusterServiceServer_SuspendCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.SuspendClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.SuspendClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_SuspendCluster_Call) Return(suspendClusterResponse *clusterv1.SuspendClusterResponse, err error) *MockClusterServiceServer_SuspendCluster_Call {
	_c.Call.Return(suspendClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_SuspendCluster_Call) RunAndReturn(run func(context1 context.Context, suspendClusterRequest *clusterv1.SuspendClusterRequest) (*clusterv1.SuspendClusterResponse, error)) *MockClusterServiceServer_SuspendCluster_Call {
	_c.Call.Return(run)
	return _c
}

// UnsuspendCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) UnsuspendCluster(context1 context.Context, unsuspendClusterRequest *clusterv1.UnsuspendClusterRequest) (*clusterv1.UnsuspendClusterResponse, error) {
	ret := _mock.Called(context1, unsuspendClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for UnsuspendCluster")
	}

	var r0 *clusterv1.UnsuspendClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.UnsuspendClusterRequest) (*clusterv1.UnsuspendClusterResponse, error)); ok {
		return returnFunc(context1, unsuspendClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.UnsuspendClusterRequest) *clusterv1.UnsuspendClusterResponse); ok {
		r0 = returnFunc(context1, unsuspendClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.UnsuspendClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.UnsuspendClusterRequest) error); ok {
		r1 = returnFunc(context1, unsuspendClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_UnsuspendCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsuspendCluster'
type MockClusterServiceServer_UnsuspendCluster_Call struct {
	*mock.Call
}

// UnsuspendCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - unsuspendClusterRequest *clusterv1.UnsuspendClusterRequest
func (_e *MockClusterServiceServer_Expecter) UnsuspendCluster(context1 interface{}, unsuspendClusterRequest interface{}) *MockClusterServiceServer_UnsuspendCluster_Call {
	return &MockClusterServiceServer_UnsuspendCluster_Call{Call: _e.mock.On("UnsuspendCluster", context1, unsuspendClusterRequest)}
}

func (_c *MockClusterServiceServer_UnsuspendCluster_Call) Run(run func(context1 context.Context, unsuspendClusterRequest *clusterv1.UnsuspendClusterRequest)) *MockClusterServiceServer_UnsuspendCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.UnsuspendClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.UnsuspendClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_UnsuspendCluster_Call) Return(unsuspendClusterResponse *clusterv1.UnsuspendClusterResponse, err error) *MockClusterServiceServer_UnsuspendCluster_Call {
	_c.Call.Return(unsuspendClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_UnsuspendCluster_Call) RunAndReturn(run func(context1 context.Context, unsuspendClusterRequest *clusterv1.UnsuspendClusterRequest) (*clusterv1.UnsuspendClusterResponse, error)) *MockClusterServiceServer_UnsuspendCluster_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCluster provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) UpdateCluster(context1 context.Context, updateClusterRequest *clusterv1.UpdateClusterRequest) (*clusterv1.UpdateClusterResponse, error) {
	ret := _mock.Called(context1, updateClusterRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCluster")
	}

	var r0 *clusterv1.UpdateClusterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.UpdateClusterRequest) (*clusterv1.UpdateClusterResponse, error)); ok {
		return returnFunc(context1, updateClusterRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *clusterv1.UpdateClusterRequest) *clusterv1.UpdateClusterResponse); ok {
		r0 = returnFunc(context1, updateClusterRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusterv1.UpdateClusterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *clusterv1.UpdateClusterRequest) error); ok {
		r1 = returnFunc(context1, updateClusterRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterServiceServer_UpdateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCluster'
type MockClusterServiceServer_UpdateCluster_Call struct {
	*mock.Call
}

// UpdateCluster is a helper method to define mock.On call
//   - context1 context.Context
//   - updateClusterRequest *clusterv1.UpdateClusterRequest
func (_e *MockClusterServiceServer_Expecter) UpdateCluster(context1 interface{}, updateClusterRequest interface{}) *MockClusterServiceServer_UpdateCluster_Call {
	return &MockClusterServiceServer_UpdateCluster_Call{Call: _e.mock.On("UpdateCluster", context1, updateClusterRequest)}
}

func (_c *MockClusterServiceServer_UpdateCluster_Call) Run(run func(context1 context.Context, updateClusterRequest *clusterv1.UpdateClusterRequest)) *MockClusterServiceServer_UpdateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *clusterv1.UpdateClusterRequest
		if args[1] != nil {
			arg1 = args[1].(*clusterv1.UpdateClusterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClusterServiceServer_UpdateCluster_Call) Return(updateClusterResponse *clusterv1.UpdateClusterResponse, err error) *MockClusterServiceServer_UpdateCluster_Call {
	_c.Call.Return(updateClusterResponse, err)
	return _c
}

func (_c *MockClusterServiceServer_UpdateCluster_Call) RunAndReturn(run func(context1 context.Context, updateClusterRequest *clusterv1.UpdateClusterRequest) (*clusterv1.UpdateClusterResponse, error)) *MockClusterServiceServer_UpdateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedClusterServiceServer provides a mock function for the type MockClusterServiceServer
func (_mock *MockClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {
	_mock.Called()
	return
}

// MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedClusterServiceServer'
type MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedClusterServiceServer is a helper method to define mock.On call
func (_e *MockClusterServiceServer_Expecter) mustEmbedUnimplementedClusterServiceServer() *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	return &MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedClusterServiceServer")}
}

func (_c *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call) Run(run func()) *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call) Return() *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call) RunAndReturn(run func()) *MockClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	_c.Run(run)
	return _c
}
