// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/cluster/backup/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackupServiceServer creates a new instance of MockBackupServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackupServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackupServiceServer {
	mock := &MockBackupServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackupServiceServer is an autogenerated mock type for the BackupServiceServer type
type MockBackupServiceServer struct {
	mock.Mock
}

type MockBackupServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackupServiceServer) EXPECT() *MockBackupServiceServer_Expecter {
	return &MockBackupServiceServer_Expecter{mock: &_m.Mock}
}

// CreateBackup provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) CreateBackup(context1 context.Context, createBackupRequest *backupv1.CreateBackupRequest) (*backupv1.CreateBackupResponse, error) {
	ret := _mock.Called(context1, createBackupRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 *backupv1.CreateBackupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.CreateBackupRequest) (*backupv1.CreateBackupResponse, error)); ok {
		return returnFunc(context1, createBackupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.CreateBackupRequest) *backupv1.CreateBackupResponse); ok {
		r0 = returnFunc(context1, createBackupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.CreateBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.CreateBackupRequest) error); ok {
		r1 = returnFunc(context1, createBackupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_CreateBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackup'
type MockBackupServiceServer_CreateBackup_Call struct {
	*mock.Call
}

// CreateBackup is a helper method to define mock.On call
//   - context1 context.Context
//   - createBackupRequest *backupv1.CreateBackupRequest
func (_e *MockBackupServiceServer_Expecter) CreateBackup(context1 interface{}, createBackupRequest interface{}) *MockBackupServiceServer_CreateBackup_Call {
	return &MockBackupServiceServer_CreateBackup_Call{Call: _e.mock.On("CreateBackup", context1, createBackupRequest)}
}

func (_c *MockBackupServiceServer_CreateBackup_Call) Run(run func(context1 context.Context, createBackupRequest *backupv1.CreateBackupRequest)) *MockBackupServiceServer_CreateBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.CreateBackupRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.CreateBackupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_CreateBackup_Call) Return(createBackupResponse *backupv1.CreateBackupResponse, err error) *MockBackupServiceServer_CreateBackup_Call {
	_c.Call.Return(createBackupResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_CreateBackup_Call) RunAndReturn(run func(context1 context.Context, createBackupRequest *backupv1.CreateBackupRequest) (*backupv1.CreateBackupResponse, error)) *MockBackupServiceServer_CreateBackup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBackupSchedule provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) CreateBackupSchedule(context1 context.Context, createBackupScheduleRequest *backupv1.CreateBackupScheduleRequest) (*backupv1.CreateBackupScheduleResponse, error) {
	ret := _mock.Called(context1, createBackupScheduleRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackupSchedule")
	}

	var r0 *backupv1.CreateBackupScheduleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.CreateBackupScheduleRequest) (*backupv1.CreateBackupScheduleResponse, error)); ok {
		return returnFunc(context1, createBackupScheduleRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.CreateBackupScheduleRequest) *backupv1.CreateBackupScheduleResponse); ok {
		r0 = returnFunc(context1, createBackupScheduleRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.CreateBackupScheduleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.CreateBackupScheduleRequest) error); ok {
		r1 = returnFunc(context1, createBackupScheduleRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_CreateBackupSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackupSchedule'
type MockBackupServiceServer_CreateBackupSchedule_Call struct {
	*mock.Call
}

// CreateBackupSchedule is a helper method to define mock.On call
//   - context1 context.Context
//   - createBackupScheduleRequest *backupv1.CreateBackupScheduleRequest
func (_e *MockBackupServiceServer_Expecter) CreateBackupSchedule(context1 interface{}, createBackupScheduleRequest interface{}) *MockBackupServiceServer_CreateBackupSchedule_Call {
	return &MockBackupServiceServer_CreateBackupSchedule_Call{Call: _e.mock.On("CreateBackupSchedule", context1, createBackupScheduleRequest)}
}

func (_c *MockBackupServiceServer_CreateBackupSchedule_Call) Run(run func(context1 context.Context, createBackupScheduleRequest *backupv1.CreateBackupScheduleRequest)) *MockBackupServiceServer_CreateBackupSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.CreateBackupScheduleRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.CreateBackupScheduleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_CreateBackupSchedule_Call) Return(createBackupScheduleResponse *backupv1.CreateBackupScheduleResponse, err error) *MockBackupServiceServer_CreateBackupSchedule_Call {
	_c.Call.Return(createBackupScheduleResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_CreateBackupSchedule_Call) RunAndReturn(run func(context1 context.Context, createBackupScheduleRequest *backupv1.CreateBackupScheduleRequest) (*backupv1.CreateBackupScheduleResponse, error)) *MockBackupServiceServer_CreateBackupSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackup provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) DeleteBackup(context1 context.Context, deleteBackupRequest *backupv1.DeleteBackupRequest) (*backupv1.DeleteBackupResponse, error) {
	ret := _mock.Called(context1, deleteBackupRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackup")
	}

	var r0 *backupv1.DeleteBackupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.DeleteBackupRequest) (*backupv1.DeleteBackupResponse, error)); ok {
		return returnFunc(context1, deleteBackupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.DeleteBackupRequest) *backupv1.DeleteBackupResponse); ok {
		r0 = returnFunc(context1, deleteBackupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.DeleteBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.DeleteBackupRequest) error); ok {
		r1 = returnFunc(context1, deleteBackupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_DeleteBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackup'
type MockBackupServiceServer_DeleteBackup_Call struct {
	*mock.Call
}

// DeleteBackup is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteBackupRequest *backupv1.DeleteBackupRequest
func (_e *MockBackupServiceServer_Expecter) DeleteBackup(context1 interface{}, deleteBackupRequest interface{}) *MockBackupServiceServer_DeleteBackup_Call {
	return &MockBackupServiceServer_DeleteBackup_Call{Call: _e.mock.On("DeleteBackup", context1, deleteBackupRequest)}
}

func (_c *MockBackupServiceServer_DeleteBackup_Call) Run(run func(context1 context.Context, deleteBackupRequest *backupv1.DeleteBackupRequest)) *MockBackupServiceServer_DeleteBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.DeleteBackupRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.DeleteBackupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_DeleteBackup_Call) Return(deleteBackupResponse *backupv1.DeleteBackupResponse, err error) *MockBackupServiceServer_DeleteBackup_Call {
	_c.Call.Return(deleteBackupResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_DeleteBackup_Call) RunAndReturn(run func(context1 context.Context, deleteBackupRequest *backupv1.DeleteBackupRequest) (*backupv1.DeleteBackupResponse, error)) *MockBackupServiceServer_DeleteBackup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackupSchedule provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) DeleteBackupSchedule(context1 context.Context, deleteBackupScheduleRequest *backupv1.DeleteBackupScheduleRequest) (*backupv1.DeleteBackupScheduleResponse, error) {
	ret := _mock.Called(context1, deleteBackupScheduleRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackupSchedule")
	}

	var r0 *backupv1.DeleteBackupScheduleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.DeleteBackupScheduleRequest) (*backupv1.DeleteBackupScheduleResponse, error)); ok {
		return returnFunc(context1, deleteBackupScheduleRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.DeleteBackupScheduleRequest) *backupv1.DeleteBackupScheduleResponse); ok {
		r0 = returnFunc(context1, deleteBackupScheduleRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.DeleteBackupScheduleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.DeleteBackupScheduleRequest) error); ok {
		r1 = returnFunc(context1, deleteBackupScheduleRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_DeleteBackupSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackupSchedule'
type MockBackupServiceServer_DeleteBackupSchedule_Call struct {
	*mock.Call
}

// DeleteBackupSchedule is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteBackupScheduleRequest *backupv1.DeleteBackupScheduleRequest
func (_e *MockBackupServiceServer_Expecter) DeleteBackupSchedule(context1 interface{}, deleteBackupScheduleRequest interface{}) *MockBackupServiceServer_DeleteBackupSchedule_Call {
	return &MockBackupServiceServer_DeleteBackupSchedule_Call{Call: _e.mock.On("DeleteBackupSchedule", context1, deleteBackupScheduleRequest)}
}

func (_c *MockBackupServiceServer_DeleteBackupSchedule_Call) Run(run func(context1 context.Context, deleteBackupScheduleRequest *backupv1.DeleteBackupScheduleRequest)) *MockBackupServiceServer_DeleteBackupSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.DeleteBackupScheduleRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.DeleteBackupScheduleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_DeleteBackupSchedule_Call) Return(deleteBackupScheduleResponse *backupv1.DeleteBackupScheduleResponse, err error) *MockBackupServiceServer_DeleteBackupSchedule_Call {
	_c.Call.Return(deleteBackupScheduleResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_DeleteBackupSchedule_Call) RunAndReturn(run func(context1 context.Context, deleteBackupScheduleRequest *backupv1.DeleteBackupScheduleRequest) (*backupv1.DeleteBackupScheduleResponse, error)) *MockBackupServiceServer_DeleteBackupSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackup provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) GetBackup(context1 context.Context, getBackupRequest *backupv1.GetBackupRequest) (*backupv1.GetBackupResponse, error) {
	ret := _mock.Called(context1, getBackupRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetBackup")
	}

	var r0 *backupv1.GetBackupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.GetBackupRequest) (*backupv1.GetBackupResponse, error)); ok {
		return returnFunc(context1, getBackupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.GetBackupRequest) *backupv1.GetBackupResponse); ok {
		r0 = returnFunc(context1, getBackupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.GetBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.GetBackupRequest) error); ok {
		r1 = returnFunc(context1, getBackupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_GetBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackup'
type MockBackupServiceServer_GetBackup_Call struct {
	*mock.Call
}

// GetBackup is a helper method to define mock.On call
//   - context1 context.Context
//   - getBackupRequest *backupv1.GetBackupRequest
func (_e *MockBackupServiceServer_Expecter) GetBackup(context1 interface{}, getBackupRequest interface{}) *MockBackupServiceServer_GetBackup_Call {
	return &MockBackupServiceServer_GetBackup_Call{Call: _e.mock.On("GetBackup", context1, getBackupRequest)}
}

func (_c *MockBackupServiceServer_GetBackup_Call) Run(run func(context1 context.Context, getBackupRequest *backupv1.GetBackupRequest)) *MockBackupServiceServer_GetBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.GetBackupRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.GetBackupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_GetBackup_Call) Return(getBackupResponse *backupv1.GetBackupResponse, err error) *MockBackupServiceServer_GetBackup_Call {
	_c.Call.Return(getBackupResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_GetBackup_Call) RunAndReturn(run func(context1 context.Context, getBackupRequest *backupv1.GetBackupRequest) (*backupv1.GetBackupResponse, error)) *MockBackupServiceServer_GetBackup_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackupSchedule provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) GetBackupSchedule(context1 context.Context, getBackupScheduleRequest *backupv1.GetBackupScheduleRequest) (*backupv1.GetBackupScheduleResponse, error) {
	ret := _mock.Called(context1, getBackupScheduleRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupSchedule")
	}

	var r0 *backupv1.GetBackupScheduleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.GetBackupScheduleRequest) (*backupv1.GetBackupScheduleResponse, error)); ok {
		return returnFunc(context1, getBackupScheduleRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.GetBackupScheduleRequest) *backupv1.GetBackupScheduleResponse); ok {
		r0 = returnFunc(context1, getBackupScheduleRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.GetBackupScheduleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.GetBackupScheduleRequest) error); ok {
		r1 = returnFunc(context1, getBackupScheduleRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_GetBackupSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupSchedule'
type MockBackupServiceServer_GetBackupSchedule_Call struct {
	*mock.Call
}

// GetBackupSchedule is a helper method to define mock.On call
//   - context1 context.Context
//   - getBackupScheduleRequest *backupv1.GetBackupScheduleRequest
func (_e *MockBackupServiceServer_Expecter) GetBackupSchedule(context1 interface{}, getBackupScheduleRequest interface{}) *MockBackupServiceServer_GetBackupSchedule_Call {
	return &MockBackupServiceServer_GetBackupSchedule_Call{Call: _e.mock.On("GetBackupSchedule", context1, getBackupScheduleRequest)}
}

func (_c *MockBackupServiceServer_GetBackupSchedule_Call) Run(run func(context1 context.Context, getBackupScheduleRequest *backupv1.GetBackupScheduleRequest)) *MockBackupServiceServer_GetBackupSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.GetBackupScheduleRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.GetBackupScheduleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_GetBackupSchedule_Call) Return(getBackupScheduleResponse *backupv1.GetBackupScheduleResponse, err error) *MockBackupServiceServer_GetBackupSchedule_Call {
	_c.Call.Return(getBackupScheduleResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_GetBackupSchedule_Call) RunAndReturn(run func(context1 context.Context, getBackupScheduleRequest *backupv1.GetBackupScheduleRequest) (*backupv1.GetBackupScheduleResponse, error)) *MockBackupServiceServer_GetBackupSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// ListBackupRestores provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) ListBackupRestores(context1 context.Context, listBackupRestoresRequest *backupv1.ListBackupRestoresRequest) (*backupv1.ListBackupRestoresResponse, error) {
	ret := _mock.Called(context1, listBackupRestoresRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListBackupRestores")
	}

	var r0 *backupv1.ListBackupRestoresResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.ListBackupRestoresRequest) (*backupv1.ListBackupRestoresResponse, error)); ok {
		return returnFunc(context1, listBackupRestoresRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.ListBackupRestoresRequest) *backupv1.ListBackupRestoresResponse); ok {
		r0 = returnFunc(context1, listBackupRestoresRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.ListBackupRestoresResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.ListBackupRestoresRequest) error); ok {
		r1 = returnFunc(context1, listBackupRestoresRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_ListBackupRestores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBackupRestores'
type MockBackupServiceServer_ListBackupRestores_Call struct {
	*mock.Call
}

// ListBackupRestores is a helper method to define mock.On call
//   - context1 context.Context
//   - listBackupRestoresRequest *backupv1.ListBackupRestoresRequest
func (_e *MockBackupServiceServer_Expecter) ListBackupRestores(context1 interface{}, listBackupRestoresRequest interface{}) *MockBackupServiceServer_ListBackupRestores_Call {
	return &MockBackupServiceServer_ListBackupRestores_Call{Call: _e.mock.On("ListBackupRestores", context1, listBackupRestoresRequest)}
}

func (_c *MockBackupServiceServer_ListBackupRestores_Call) Run(run func(context1 context.Context, listBackupRestoresRequest *backupv1.ListBackupRestoresRequest)) *MockBackupServiceServer_ListBackupRestores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.ListBackupRestoresRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.ListBackupRestoresRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_ListBackupRestores_Call) Return(listBackupRestoresResponse *backupv1.ListBackupRestoresResponse, err error) *MockBackupServiceServer_ListBackupRestores_Call {
	_c.Call.Return(listBackupRestoresResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_ListBackupRestores_Call) RunAndReturn(run func(context1 context.Context, listBackupRestoresRequest *backupv1.ListBackupRestoresRequest) (*backupv1.ListBackupRestoresResponse, error)) *MockBackupServiceServer_ListBackupRestores_Call {
	_c.Call.Return(run)
	return _c
}

// ListBackupSchedules provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) ListBackupSchedules(context1 context.Context, listBackupSchedulesRequest *backupv1.ListBackupSchedulesRequest) (*backupv1.ListBackupSchedulesResponse, error) {
	ret := _mock.Called(context1, listBackupSchedulesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListBackupSchedules")
	}

	var r0 *backupv1.ListBackupSchedulesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.ListBackupSchedulesRequest) (*backupv1.ListBackupSchedulesResponse, error)); ok {
		return returnFunc(context1, listBackupSchedulesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.ListBackupSchedulesRequest) *backupv1.ListBackupSchedulesResponse); ok {
		r0 = returnFunc(context1, listBackupSchedulesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.ListBackupSchedulesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.ListBackupSchedulesRequest) error); ok {
		r1 = returnFunc(context1, listBackupSchedulesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_ListBackupSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBackupSchedules'
type MockBackupServiceServer_ListBackupSchedules_Call struct {
	*mock.Call
}

// ListBackupSchedules is a helper method to define mock.On call
//   - context1 context.Context
//   - listBackupSchedulesRequest *backupv1.ListBackupSchedulesRequest
func (_e *MockBackupServiceServer_Expecter) ListBackupSchedules(context1 interface{}, listBackupSchedulesRequest interface{}) *MockBackupServiceServer_ListBackupSchedules_Call {
	return &MockBackupServiceServer_ListBackupSchedules_Call{Call: _e.mock.On("ListBackupSchedules", context1, listBackupSchedulesRequest)}
}

func (_c *MockBackupServiceServer_ListBackupSchedules_Call) Run(run func(context1 context.Context, listBackupSchedulesRequest *backupv1.ListBackupSchedulesRequest)) *MockBackupServiceServer_ListBackupSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.ListBackupSchedulesRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.ListBackupSchedulesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_ListBackupSchedules_Call) Return(listBackupSchedulesResponse *backupv1.ListBackupSchedulesResponse, err error) *MockBackupServiceServer_ListBackupSchedules_Call {
	_c.Call.Return(listBackupSchedulesResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_ListBackupSchedules_Call) RunAndReturn(run func(context1 context.Context, listBackupSchedulesRequest *backupv1.ListBackupSchedulesRequest) (*backupv1.ListBackupSchedulesResponse, error)) *MockBackupServiceServer_ListBackupSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// ListBackups provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) ListBackups(context1 context.Context, listBackupsRequest *backupv1.ListBackupsRequest) (*backupv1.ListBackupsResponse, error) {
	ret := _mock.Called(context1, listBackupsRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListBackups")
	}

	var r0 *backupv1.ListBackupsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.ListBackupsRequest) (*backupv1.ListBackupsResponse, error)); ok {
		return returnFunc(context1, listBackupsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.ListBackupsRequest) *backupv1.ListBackupsResponse); ok {
		r0 = returnFunc(context1, listBackupsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.ListBackupsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.ListBackupsRequest) error); ok {
		r1 = returnFunc(context1, listBackupsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_ListBackups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBackups'
type MockBackupServiceServer_ListBackups_Call struct {
	*mock.Call
}

// ListBackups is a helper method to define mock.On call
//   - context1 context.Context
//   - listBackupsRequest *backupv1.ListBackupsRequest
func (_e *MockBackupServiceServer_Expecter) ListBackups(context1 interface{}, listBackupsRequest interface{}) *MockBackupServiceServer_ListBackups_Call {
	return &MockBackupServiceServer_ListBackups_Call{Call: _e.mock.On("ListBackups", context1, listBackupsRequest)}
}

func (_c *MockBackupServiceServer_ListBackups_Call) Run(run func(context1 context.Context, listBackupsRequest *backupv1.ListBackupsRequest)) *MockBackupServiceServer_ListBackups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.ListBackupsRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.ListBackupsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_ListBackups_Call) Return(listBackupsResponse *backupv1.ListBackupsResponse, err error) *MockBackupServiceServer_ListBackups_Call {
	_c.Call.Return(listBackupsResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_ListBackups_Call) RunAndReturn(run func(context1 context.Context, listBackupsRequest *backupv1.ListBackupsRequest) (*backupv1.ListBackupsResponse, error)) *MockBackupServiceServer_ListBackups_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreBackup provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) RestoreBackup(context1 context.Context, restoreBackupRequest *backupv1.RestoreBackupRequest) (*backupv1.RestoreBackupResponse, error) {
	ret := _mock.Called(context1, restoreBackupRequest)

	if len(ret) == 0 {
		panic("no return value specified for RestoreBackup")
	}

	var r0 *backupv1.RestoreBackupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.RestoreBackupRequest) (*backupv1.RestoreBackupResponse, error)); ok {
		return returnFunc(context1, restoreBackupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.RestoreBackupRequest) *backupv1.RestoreBackupResponse); ok {
		r0 = returnFunc(context1, restoreBackupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.RestoreBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.RestoreBackupRequest) error); ok {
		r1 = returnFunc(context1, restoreBackupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_RestoreBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreBackup'
type MockBackupServiceServer_RestoreBackup_Call struct {
	*mock.Call
}

// RestoreBackup is a helper method to define mock.On call
//   - context1 context.Context
//   - restoreBackupRequest *backupv1.RestoreBackupRequest
func (_e *MockBackupServiceServer_Expecter) RestoreBackup(context1 interface{}, restoreBackupRequest interface{}) *MockBackupServiceServer_RestoreBackup_Call {
	return &MockBackupServiceServer_RestoreBackup_Call{Call: _e.mock.On("RestoreBackup", context1, restoreBackupRequest)}
}

func (_c *MockBackupServiceServer_RestoreBackup_Call) Run(run func(context1 context.Context, restoreBackupRequest *backupv1.RestoreBackupRequest)) *MockBackupServiceServer_RestoreBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.RestoreBackupRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.RestoreBackupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_RestoreBackup_Call) Return(restoreBackupResponse *backupv1.RestoreBackupResponse, err error) *MockBackupServiceServer_RestoreBackup_Call {
	_c.Call.Return(restoreBackupResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_RestoreBackup_Call) RunAndReturn(run func(context1 context.Context, restoreBackupRequest *backupv1.RestoreBackupRequest) (*backupv1.RestoreBackupResponse, error)) *MockBackupServiceServer_RestoreBackup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBackupSchedule provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) UpdateBackupSchedule(context1 context.Context, updateBackupScheduleRequest *backupv1.UpdateBackupScheduleRequest) (*backupv1.UpdateBackupScheduleResponse, error) {
	ret := _mock.Called(context1, updateBackupScheduleRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackupSchedule")
	}

	var r0 *backupv1.UpdateBackupScheduleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.UpdateBackupScheduleRequest) (*backupv1.UpdateBackupScheduleResponse, error)); ok {
		return returnFunc(context1, updateBackupScheduleRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *backupv1.UpdateBackupScheduleRequest) *backupv1.UpdateBackupScheduleResponse); ok {
		r0 = returnFunc(context1, updateBackupScheduleRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupv1.UpdateBackupScheduleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *backupv1.UpdateBackupScheduleRequest) error); ok {
		r1 = returnFunc(context1, updateBackupScheduleRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupServiceServer_UpdateBackupSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBackupSchedule'
type MockBackupServiceServer_UpdateBackupSchedule_Call struct {
	*mock.Call
}

// UpdateBackupSchedule is a helper method to define mock.On call
//   - context1 context.Context
//   - updateBackupScheduleRequest *backupv1.UpdateBackupScheduleRequest
func (_e *MockBackupServiceServer_Expecter) UpdateBackupSchedule(context1 interface{}, updateBackupScheduleRequest interface{}) *MockBackupServiceServer_UpdateBackupSchedule_Call {
	return &MockBackupServiceServer_UpdateBackupSchedule_Call{Call: _e.mock.On("UpdateBackupSchedule", context1, updateBackupScheduleRequest)}
}

func (_c *MockBackupServiceServer_UpdateBackupSchedule_Call) Run(run func(context1 context.Context, updateBackupScheduleRequest *backupv1.UpdateBackupScheduleRequest)) *MockBackupServiceServer_UpdateBackupSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *backupv1.UpdateBackupScheduleRequest
		if args[1] != nil {
			arg1 = args[1].(*backupv1.UpdateBackupScheduleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupServiceServer_UpdateBackupSchedule_Call) Return(updateBackupScheduleResponse *backupv1.UpdateBackupScheduleResponse, err error) *MockBackupServiceServer_UpdateBackupSchedule_Call {
	_c.Call.Return(updateBackupScheduleResponse, err)
	return _c
}

func (_c *MockBackupServiceServer_UpdateBackupSchedule_Call) RunAndReturn(run func(context1 context.Context, updateBackupScheduleRequest *backupv1.UpdateBackupScheduleRequest) (*backupv1.UpdateBackupScheduleResponse, error)) *MockBackupServiceServer_UpdateBackupSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedBackupServiceServer provides a mock function for the type MockBackupServiceServer
func (_mock *MockBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {
	_mock.Called()
	return
}

// MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedBackupServiceServer'
type MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedBackupServiceServer is a helper method to define mock.On call
func (_e *MockBackupServiceServer_Expecter) mustEmbedUnimplementedBackupServiceServer() *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call {
	return &MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedBackupServiceServer")}
}

func (_c *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call) Run(run func()) *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call) Return() *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call) RunAndReturn(run func()) *MockBackupServiceServer_mustEmbedUnimplementedBackupServiceServer_Call {
	_c.Run(run)
	return _c
}
