// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/platform/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlatformServiceServer creates a new instance of MockPlatformServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatformServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatformServiceServer {
	mock := &MockPlatformServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlatformServiceServer is an autogenerated mock type for the PlatformServiceServer type
type MockPlatformServiceServer struct {
	mock.Mock
}

type MockPlatformServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatformServiceServer) EXPECT() *MockPlatformServiceServer_Expecter {
	return &MockPlatformServiceServer_Expecter{mock: &_m.Mock}
}

// GetCloudProviderRegion provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) GetCloudProviderRegion(context1 context.Context, getCloudProviderRegionRequest *platformv1.GetCloudProviderRegionRequest) (*platformv1.GetCloudProviderRegionResponse, error) {
	ret := _mock.Called(context1, getCloudProviderRegionRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetCloudProviderRegion")
	}

	var r0 *platformv1.GetCloudProviderRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.GetCloudProviderRegionRequest) (*platformv1.GetCloudProviderRegionResponse, error)); ok {
		return returnFunc(context1, getCloudProviderRegionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.GetCloudProviderRegionRequest) *platformv1.GetCloudProviderRegionResponse); ok {
		r0 = returnFunc(context1, getCloudProviderRegionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformv1.GetCloudProviderRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *platformv1.GetCloudProviderRegionRequest) error); ok {
		r1 = returnFunc(context1, getCloudProviderRegionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformServiceServer_GetCloudProviderRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCloudProviderRegion'
type MockPlatformServiceServer_GetCloudProviderRegion_Call struct {
	*mock.Call
}

// GetCloudProviderRegion is a helper method to define mock.On call
//   - context1 context.Context
//   - getCloudProviderRegionRequest *platformv1.GetCloudProviderRegionRequest
func (_e *MockPlatformServiceServer_Expecter) GetCloudProviderRegion(context1 interface{}, getCloudProviderRegionRequest interface{}) *MockPlatformServiceServer_GetCloudProviderRegion_Call {
	return &MockPlatformServiceServer_GetCloudProviderRegion_Call{Call: _e.mock.On("GetCloudProviderRegion", context1, getCloudProviderRegionRequest)}
}

func (_c *MockPlatformServiceServer_GetCloudProviderRegion_Call) Run(run func(context1 context.Context, getCloudProviderRegionRequest *platformv1.GetCloudProviderRegionRequest)) *MockPlatformServiceServer_GetCloudProviderRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *platformv1.GetCloudProviderRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*platformv1.GetCloudProviderRegionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformServiceServer_GetCloudProviderRegion_Call) Return(getCloudProviderRegionResponse *platformv1.GetCloudProviderRegionResponse, err error) *MockPlatformServiceServer_GetCloudProviderRegion_Call {
	_c.Call.Return(getCloudProviderRegionResponse, err)
	return _c
}

func (_c *MockPlatformServiceServer_GetCloudProviderRegion_Call) RunAndReturn(run func(context1 context.Context, getCloudProviderRegionRequest *platformv1.GetCloudProviderRegionRequest) (*platformv1.GetCloudProviderRegionResponse, error)) *MockPlatformServiceServer_GetCloudProviderRegion_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalCloudProviderRegion provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) GetGlobalCloudProviderRegion(context1 context.Context, getGlobalCloudProviderRegionRequest *platformv1.GetGlobalCloudProviderRegionRequest) (*platformv1.GetGlobalCloudProviderRegionResponse, error) {
	ret := _mock.Called(context1, getGlobalCloudProviderRegionRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalCloudProviderRegion")
	}

	var r0 *platformv1.GetGlobalCloudProviderRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.GetGlobalCloudProviderRegionRequest) (*platformv1.GetGlobalCloudProviderRegionResponse, error)); ok {
		return returnFunc(context1, getGlobalCloudProviderRegionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.GetGlobalCloudProviderRegionRequest) *platformv1.GetGlobalCloudProviderRegionResponse); ok {
		r0 = returnFunc(context1, getGlobalCloudProviderRegionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformv1.GetGlobalCloudProviderRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *platformv1.GetGlobalCloudProviderRegionRequest) error); ok {
		r1 = returnFunc(context1, getGlobalCloudProviderRegionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalCloudProviderRegion'
type MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call struct {
	*mock.Call
}

// GetGlobalCloudProviderRegion is a helper method to define mock.On call
//   - context1 context.Context
//   - getGlobalCloudProviderRegionRequest *platformv1.GetGlobalCloudProviderRegionRequest
func (_e *MockPlatformServiceServer_Expecter) GetGlobalCloudProviderRegion(context1 interface{}, getGlobalCloudProviderRegionRequest interface{}) *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call {
	return &MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call{Call: _e.mock.On("GetGlobalCloudProviderRegion", context1, getGlobalCloudProviderRegionRequest)}
}

func (_c *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call) Run(run func(context1 context.Context, getGlobalCloudProviderRegionRequest *platformv1.GetGlobalCloudProviderRegionRequest)) *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *platformv1.GetGlobalCloudProviderRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*platformv1.GetGlobalCloudProviderRegionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call) Return(getGlobalCloudProviderRegionResponse *platformv1.GetGlobalCloudProviderRegionResponse, err error) *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call {
	_c.Call.Return(getGlobalCloudProviderRegionResponse, err)
	return _c
}

func (_c *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call) RunAndReturn(run func(context1 context.Context, getGlobalCloudProviderRegionRequest *platformv1.GetGlobalCloudProviderRegionRequest) (*platformv1.GetGlobalCloudProviderRegionResponse, error)) *MockPlatformServiceServer_GetGlobalCloudProviderRegion_Call {
	_c.Call.Return(run)
	return _c
}

// ListCloudProviderRegions provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) ListCloudProviderRegions(context1 context.Context, listCloudProviderRegionsRequest *platformv1.ListCloudProviderRegionsRequest) (*platformv1.ListCloudProviderRegionsResponse, error) {
	ret := _mock.Called(context1, listCloudProviderRegionsRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListCloudProviderRegions")
	}

	var r0 *platformv1.ListCloudProviderRegionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListCloudProviderRegionsRequest) (*platformv1.ListCloudProviderRegionsResponse, error)); ok {
		return returnFunc(context1, listCloudProviderRegionsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListCloudProviderRegionsRequest) *platformv1.ListCloudProviderRegionsResponse); ok {
		r0 = returnFunc(context1, listCloudProviderRegionsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformv1.ListCloudProviderRegionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *platformv1.ListCloudProviderRegionsRequest) error); ok {
		r1 = returnFunc(context1, listCloudProviderRegionsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformServiceServer_ListCloudProviderRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCloudProviderRegions'
type MockPlatformServiceServer_ListCloudProviderRegions_Call struct {
	*mock.Call
}

// ListCloudProviderRegions is a helper method to define mock.On call
//   - context1 context.Context
//   - listCloudProviderRegionsRequest *platformv1.ListCloudProviderRegionsRequest
func (_e *MockPlatformServiceServer_Expecter) ListCloudProviderRegions(context1 interface{}, listCloudProviderRegionsRequest interface{}) *MockPlatformServiceServer_ListCloudProviderRegions_Call {
	return &MockPlatformServiceServer_ListCloudProviderRegions_Call{Call: _e.mock.On("ListCloudProviderRegions", context1, listCloudProviderRegionsRequest)}
}

func (_c *MockPlatformServiceServer_ListCloudProviderRegions_Call) Run(run func(context1 context.Context, listCloudProviderRegionsRequest *platformv1.ListCloudProviderRegionsRequest)) *MockPlatformServiceServer_ListCloudProviderRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *platformv1.ListCloudProviderRegionsRequest
		if args[1] != nil {
			arg1 = args[1].(*platformv1.ListCloudProviderRegionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformServiceServer_ListCloudProviderRegions_Call) Return(listCloudProviderRegionsResponse *platformv1.ListCloudProviderRegionsResponse, err error) *MockPlatformServiceServer_ListCloudProviderRegions_Call {
	_c.Call.Return(listCloudProviderRegionsResponse, err)
	return _c
}

func (_c *MockPlatformServiceServer_ListCloudProviderRegions_Call) RunAndReturn(run func(context1 context.Context, listCloudProviderRegionsRequest *platformv1.ListCloudProviderRegionsRequest) (*platformv1.ListCloudProviderRegionsResponse, error)) *MockPlatformServiceServer_ListCloudProviderRegions_Call {
	_c.Call.Return(run)
	return _c
}

// ListCloudProviders provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) ListCloudProviders(context1 context.Context, listCloudProvidersRequest *platformv1.ListCloudProvidersRequest) (*platformv1.ListCloudProvidersResponse, error) {
	ret := _mock.Called(context1, listCloudProvidersRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListCloudProviders")
	}

	var r0 *platformv1.ListCloudProvidersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListCloudProvidersRequest) (*platformv1.ListCloudProvidersResponse, error)); ok {
		return returnFunc(context1, listCloudProvidersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListCloudProvidersRequest) *platformv1.ListCloudProvidersResponse); ok {
		r0 = returnFunc(context1, listCloudProvidersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformv1.ListCloudProvidersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *platformv1.ListCloudProvidersRequest) error); ok {
		r1 = returnFunc(context1, listCloudProvidersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformServiceServer_ListCloudProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCloudProviders'
type MockPlatformServiceServer_ListCloudProviders_Call struct {
	*mock.Call
}

// ListCloudProviders is a helper method to define mock.On call
//   - context1 context.Context
//   - listCloudProvidersRequest *platformv1.ListCloudProvidersRequest
func (_e *MockPlatformServiceServer_Expecter) ListCloudProviders(context1 interface{}, listCloudProvidersRequest interface{}) *MockPlatformServiceServer_ListCloudProviders_Call {
	return &MockPlatformServiceServer_ListCloudProviders_Call{Call: _e.mock.On("ListCloudProviders", context1, listCloudProvidersRequest)}
}

func (_c *MockPlatformServiceServer_ListCloudProviders_Call) Run(run func(context1 context.Context, listCloudProvidersRequest *platformv1.ListCloudProvidersRequest)) *MockPlatformServiceServer_ListCloudProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *platformv1.ListCloudProvidersRequest
		if args[1] != nil {
			arg1 = args[1].(*platformv1.ListCloudProvidersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformServiceServer_ListCloudProviders_Call) Return(listCloudProvidersResponse *platformv1.ListCloudProvidersResponse, err error) *MockPlatformServiceServer_ListCloudProviders_Call {
	_c.Call.Return(listCloudProvidersResponse, err)
	return _c
}

func (_c *MockPlatformServiceServer_ListCloudProviders_Call) RunAndReturn(run func(context1 context.Context, listCloudProvidersRequest *platformv1.ListCloudProvidersRequest) (*platformv1.ListCloudProvidersResponse, error)) *MockPlatformServiceServer_ListCloudProviders_Call {
	_c.Call.Return(run)
	return _c
}

// ListGlobalCloudProviderRegions provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) ListGlobalCloudProviderRegions(context1 context.Context, listGlobalCloudProviderRegionsRequest *platformv1.ListGlobalCloudProviderRegionsRequest) (*platformv1.ListGlobalCloudProviderRegionsResponse, error) {
	ret := _mock.Called(context1, listGlobalCloudProviderRegionsRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListGlobalCloudProviderRegions")
	}

	var r0 *platformv1.ListGlobalCloudProviderRegionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListGlobalCloudProviderRegionsRequest) (*platformv1.ListGlobalCloudProviderRegionsResponse, error)); ok {
		return returnFunc(context1, listGlobalCloudProviderRegionsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListGlobalCloudProviderRegionsRequest) *platformv1.ListGlobalCloudProviderRegionsResponse); ok {
		r0 = returnFunc(context1, listGlobalCloudProviderRegionsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformv1.ListGlobalCloudProviderRegionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *platformv1.ListGlobalCloudProviderRegionsRequest) error); ok {
		r1 = returnFunc(context1, listGlobalCloudProviderRegionsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGlobalCloudProviderRegions'
type MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call struct {
	*mock.Call
}

// ListGlobalCloudProviderRegions is a helper method to define mock.On call
//   - context1 context.Context
//   - listGlobalCloudProviderRegionsRequest *platformv1.ListGlobalCloudProviderRegionsRequest
func (_e *MockPlatformServiceServer_Expecter) ListGlobalCloudProviderRegions(context1 interface{}, listGlobalCloudProviderRegionsRequest interface{}) *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call {
	return &MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call{Call: _e.mock.On("ListGlobalCloudProviderRegions", context1, listGlobalCloudProviderRegionsRequest)}
}

func (_c *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call) Run(run func(context1 context.Context, listGlobalCloudProviderRegionsRequest *platformv1.ListGlobalCloudProviderRegionsRequest)) *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *platformv1.ListGlobalCloudProviderRegionsRequest
		if args[1] != nil {
			arg1 = args[1].(*platformv1.ListGlobalCloudProviderRegionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call) Return(listGlobalCloudProviderRegionsResponse *platformv1.ListGlobalCloudProviderRegionsResponse, err error) *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call {
	_c.Call.Return(listGlobalCloudProviderRegionsResponse, err)
	return _c
}

func (_c *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call) RunAndReturn(run func(context1 context.Context, listGlobalCloudProviderRegionsRequest *platformv1.ListGlobalCloudProviderRegionsRequest) (*platformv1.ListGlobalCloudProviderRegionsResponse, error)) *MockPlatformServiceServer_ListGlobalCloudProviderRegions_Call {
	_c.Call.Return(run)
	return _c
}

// ListGlobalCloudProviders provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) ListGlobalCloudProviders(context1 context.Context, listGlobalCloudProvidersRequest *platformv1.ListGlobalCloudProvidersRequest) (*platformv1.ListGlobalCloudProvidersResponse, error) {
	ret := _mock.Called(context1, listGlobalCloudProvidersRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListGlobalCloudProviders")
	}

	var r0 *platformv1.ListGlobalCloudProvidersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListGlobalCloudProvidersRequest) (*platformv1.ListGlobalCloudProvidersResponse, error)); ok {
		return returnFunc(context1, listGlobalCloudProvidersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *platformv1.ListGlobalCloudProvidersRequest) *platformv1.ListGlobalCloudProvidersResponse); ok {
		r0 = returnFunc(context1, listGlobalCloudProvidersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformv1.ListGlobalCloudProvidersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *platformv1.ListGlobalCloudProvidersRequest) error); ok {
		r1 = returnFunc(context1, listGlobalCloudProvidersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformServiceServer_ListGlobalCloudProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGlobalCloudProviders'
type MockPlatformServiceServer_ListGlobalCloudProviders_Call struct {
	*mock.Call
}

// ListGlobalCloudProviders is a helper method to define mock.On call
//   - context1 context.Context
//   - listGlobalCloudProvidersRequest *platformv1.ListGlobalCloudProvidersRequest
func (_e *MockPlatformServiceServer_Expecter) ListGlobalCloudProviders(context1 interface{}, listGlobalCloudProvidersRequest interface{}) *MockPlatformServiceServer_ListGlobalCloudProviders_Call {
	return &MockPlatformServiceServer_ListGlobalCloudProviders_Call{Call: _e.mock.On("ListGlobalCloudProviders", context1, listGlobalCloudProvidersRequest)}
}

func (_c *MockPlatformServiceServer_ListGlobalCloudProviders_Call) Run(run func(context1 context.Context, listGlobalCloudProvidersRequest *platformv1.ListGlobalCloudProvidersRequest)) *MockPlatformServiceServer_ListGlobalCloudProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *platformv1.ListGlobalCloudProvidersRequest
		if args[1] != nil {
			arg1 = args[1].(*platformv1.ListGlobalCloudProvidersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformServiceServer_ListGlobalCloudProviders_Call) Return(listGlobalCloudProvidersResponse *platformv1.ListGlobalCloudProvidersResponse, err error) *MockPlatformServiceServer_ListGlobalCloudProviders_Call {
	_c.Call.Return(listGlobalCloudProvidersResponse, err)
	return _c
}

func (_c *MockPlatformServiceServer_ListGlobalCloudProviders_Call) RunAndReturn(run func(context1 context.Context, listGlobalCloudProvidersRequest *platformv1.ListGlobalCloudProvidersRequest) (*platformv1.ListGlobalCloudProvidersResponse, error)) *MockPlatformServiceServer_ListGlobalCloudProviders_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedPlatformServiceServer provides a mock function for the type MockPlatformServiceServer
func (_mock *MockPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {
	_mock.Called()
	return
}

// MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPlatformServiceServer'
type MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPlatformServiceServer is a helper method to define mock.On call
func (_e *MockPlatformServiceServer_Expecter) mustEmbedUnimplementedPlatformServiceServer() *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call {
	return &MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPlatformServiceServer")}
}

func (_c *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call) Run(run func()) *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call) Return() *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call) RunAndReturn(run func()) *MockPlatformServiceServer_mustEmbedUnimplementedPlatformServiceServer_Call {
	_c.Run(run)
	return _c
}
