// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/cluster/auth/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabaseApiKeyServiceServer creates a new instance of MockDatabaseApiKeyServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseApiKeyServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseApiKeyServiceServer {
	mock := &MockDatabaseApiKeyServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseApiKeyServiceServer is an autogenerated mock type for the DatabaseApiKeyServiceServer type
type MockDatabaseApiKeyServiceServer struct {
	mock.Mock
}

type MockDatabaseApiKeyServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseApiKeyServiceServer) EXPECT() *MockDatabaseApiKeyServiceServer_Expecter {
	return &MockDatabaseApiKeyServiceServer_Expecter{mock: &_m.Mock}
}

// CreateDatabaseApiKey provides a mock function for the type MockDatabaseApiKeyServiceServer
func (_mock *MockDatabaseApiKeyServiceServer) CreateDatabaseApiKey(context1 context.Context, createDatabaseApiKeyRequest *authv2.CreateDatabaseApiKeyRequest) (*authv2.CreateDatabaseApiKeyResponse, error) {
	ret := _mock.Called(context1, createDatabaseApiKeyRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatabaseApiKey")
	}

	var r0 *authv2.CreateDatabaseApiKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv2.CreateDatabaseApiKeyRequest) (*authv2.CreateDatabaseApiKeyResponse, error)); ok {
		return returnFunc(context1, createDatabaseApiKeyRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv2.CreateDatabaseApiKeyRequest) *authv2.CreateDatabaseApiKeyResponse); ok {
		r0 = returnFunc(context1, createDatabaseApiKeyRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv2.CreateDatabaseApiKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv2.CreateDatabaseApiKeyRequest) error); ok {
		r1 = returnFunc(context1, createDatabaseApiKeyRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatabaseApiKey'
type MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call struct {
	*mock.Call
}

// CreateDatabaseApiKey is a helper method to define mock.On call
//   - context1 context.Context
//   - createDatabaseApiKeyRequest *authv2.CreateDatabaseApiKeyRequest
func (_e *MockDatabaseApiKeyServiceServer_Expecter) CreateDatabaseApiKey(context1 interface{}, createDatabaseApiKeyRequest interface{}) *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call {
	return &MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call{Call: _e.mock.On("CreateDatabaseApiKey", context1, createDatabaseApiKeyRequest)}
}

func (_c *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call) Run(run func(context1 context.Context, createDatabaseApiKeyRequest *authv2.CreateDatabaseApiKeyRequest)) *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv2.CreateDatabaseApiKeyRequest
		if args[1] != nil {
			arg1 = args[1].(*authv2.CreateDatabaseApiKeyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call) Return(createDatabaseApiKeyResponse *authv2.CreateDatabaseApiKeyResponse, err error) *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call {
	_c.Call.Return(createDatabaseApiKeyResponse, err)
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call) RunAndReturn(run func(context1 context.Context, createDatabaseApiKeyRequest *authv2.CreateDatabaseApiKeyRequest) (*authv2.CreateDatabaseApiKeyResponse, error)) *MockDatabaseApiKeyServiceServer_CreateDatabaseApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDatabaseApiKey provides a mock function for the type MockDatabaseApiKeyServiceServer
func (_mock *MockDatabaseApiKeyServiceServer) DeleteDatabaseApiKey(context1 context.Context, deleteDatabaseApiKeyRequest *authv2.DeleteDatabaseApiKeyRequest) (*authv2.DeleteDatabaseApiKeyResponse, error) {
	ret := _mock.Called(context1, deleteDatabaseApiKeyRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDatabaseApiKey")
	}

	var r0 *authv2.DeleteDatabaseApiKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv2.DeleteDatabaseApiKeyRequest) (*authv2.DeleteDatabaseApiKeyResponse, error)); ok {
		return returnFunc(context1, deleteDatabaseApiKeyRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv2.DeleteDatabaseApiKeyRequest) *authv2.DeleteDatabaseApiKeyResponse); ok {
		r0 = returnFunc(context1, deleteDatabaseApiKeyRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv2.DeleteDatabaseApiKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv2.DeleteDatabaseApiKeyRequest) error); ok {
		r1 = returnFunc(context1, deleteDatabaseApiKeyRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDatabaseApiKey'
type MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call struct {
	*mock.Call
}

// DeleteDatabaseApiKey is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteDatabaseApiKeyRequest *authv2.DeleteDatabaseApiKeyRequest
func (_e *MockDatabaseApiKeyServiceServer_Expecter) DeleteDatabaseApiKey(context1 interface{}, deleteDatabaseApiKeyRequest interface{}) *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call {
	return &MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call{Call: _e.mock.On("DeleteDatabaseApiKey", context1, deleteDatabaseApiKeyRequest)}
}

func (_c *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call) Run(run func(context1 context.Context, deleteDatabaseApiKeyRequest *authv2.DeleteDatabaseApiKeyRequest)) *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv2.DeleteDatabaseApiKeyRequest
		if args[1] != nil {
			arg1 = args[1].(*authv2.DeleteDatabaseApiKeyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call) Return(deleteDatabaseApiKeyResponse *authv2.DeleteDatabaseApiKeyResponse, err error) *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call {
	_c.Call.Return(deleteDatabaseApiKeyResponse, err)
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call) RunAndReturn(run func(context1 context.Context, deleteDatabaseApiKeyRequest *authv2.DeleteDatabaseApiKeyRequest) (*authv2.DeleteDatabaseApiKeyResponse, error)) *MockDatabaseApiKeyServiceServer_DeleteDatabaseApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListDatabaseApiKeys provides a mock function for the type MockDatabaseApiKeyServiceServer
func (_mock *MockDatabaseApiKeyServiceServer) ListDatabaseApiKeys(context1 context.Context, listDatabaseApiKeysRequest *authv2.ListDatabaseApiKeysRequest) (*authv2.ListDatabaseApiKeysResponse, error) {
	ret := _mock.Called(context1, listDatabaseApiKeysRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListDatabaseApiKeys")
	}

	var r0 *authv2.ListDatabaseApiKeysResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv2.ListDatabaseApiKeysRequest) (*authv2.ListDatabaseApiKeysResponse, error)); ok {
		return returnFunc(context1, listDatabaseApiKeysRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv2.ListDatabaseApiKeysRequest) *authv2.ListDatabaseApiKeysResponse); ok {
		r0 = returnFunc(context1, listDatabaseApiKeysRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv2.ListDatabaseApiKeysResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv2.ListDatabaseApiKeysRequest) error); ok {
		r1 = returnFunc(context1, listDatabaseApiKeysRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDatabaseApiKeys'
type MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call struct {
	*mock.Call
}

// ListDatabaseApiKeys is a helper method to define mock.On call
//   - context1 context.Context
//   - listDatabaseApiKeysRequest *authv2.ListDatabaseApiKeysRequest
func (_e *MockDatabaseApiKeyServiceServer_Expecter) ListDatabaseApiKeys(context1 interface{}, listDatabaseApiKeysRequest interface{}) *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call {
	return &MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call{Call: _e.mock.On("ListDatabaseApiKeys", context1, listDatabaseApiKeysRequest)}
}

func (_c *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call) Run(run func(context1 context.Context, listDatabaseApiKeysRequest *authv2.ListDatabaseApiKeysRequest)) *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv2.ListDatabaseApiKeysRequest
		if args[1] != nil {
			arg1 = args[1].(*authv2.ListDatabaseApiKeysRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call) Return(listDatabaseApiKeysResponse *authv2.ListDatabaseApiKeysResponse, err error) *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call {
	_c.Call.Return(listDatabaseApiKeysResponse, err)
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call) RunAndReturn(run func(context1 context.Context, listDatabaseApiKeysRequest *authv2.ListDatabaseApiKeysRequest) (*authv2.ListDatabaseApiKeysResponse, error)) *MockDatabaseApiKeyServiceServer_ListDatabaseApiKeys_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedDatabaseApiKeyServiceServer provides a mock function for the type MockDatabaseApiKeyServiceServer
func (_mock *MockDatabaseApiKeyServiceServer) mustEmbedUnimplementedDatabaseApiKeyServiceServer() {
	_mock.Called()
	return
}

// MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDatabaseApiKeyServiceServer'
type MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDatabaseApiKeyServiceServer is a helper method to define mock.On call
func (_e *MockDatabaseApiKeyServiceServer_Expecter) mustEmbedUnimplementedDatabaseApiKeyServiceServer() *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call {
	return &MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDatabaseApiKeyServiceServer")}
}

func (_c *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call) Run(run func()) *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call) Return() *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call) RunAndReturn(run func()) *MockDatabaseApiKeyServiceServer_mustEmbedUnimplementedDatabaseApiKeyServiceServer_Call {
	_c.Run(run)
	return _c
}
