// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/qdrant/qdrant-cloud-public-api/gen/go/qdrant/cloud/booking/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingServiceServer creates a new instance of MockBookingServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingServiceServer {
	mock := &MockBookingServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingServiceServer is an autogenerated mock type for the BookingServiceServer type
type MockBookingServiceServer struct {
	mock.Mock
}

type MockBookingServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingServiceServer) EXPECT() *MockBookingServiceServer_Expecter {
	return &MockBookingServiceServer_Expecter{mock: &_m.Mock}
}

// GetBackupQuote provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) GetBackupQuote(context1 context.Context, getBackupQuoteRequest *bookingv1.GetBackupQuoteRequest) (*bookingv1.GetBackupQuoteResponse, error) {
	ret := _mock.Called(context1, getBackupQuoteRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupQuote")
	}

	var r0 *bookingv1.GetBackupQuoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.GetBackupQuoteRequest) (*bookingv1.GetBackupQuoteResponse, error)); ok {
		return returnFunc(context1, getBackupQuoteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.GetBackupQuoteRequest) *bookingv1.GetBackupQuoteResponse); ok {
		r0 = returnFunc(context1, getBackupQuoteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.GetBackupQuoteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.GetBackupQuoteRequest) error); ok {
		r1 = returnFunc(context1, getBackupQuoteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_GetBackupQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupQuote'
type MockBookingServiceServer_GetBackupQuote_Call struct {
	*mock.Call
}

// GetBackupQuote is a helper method to define mock.On call
//   - context1 context.Context
//   - getBackupQuoteRequest *bookingv1.GetBackupQuoteRequest
func (_e *MockBookingServiceServer_Expecter) GetBackupQuote(context1 interface{}, getBackupQuoteRequest interface{}) *MockBookingServiceServer_GetBackupQuote_Call {
	return &MockBookingServiceServer_GetBackupQuote_Call{Call: _e.mock.On("GetBackupQuote", context1, getBackupQuoteRequest)}
}

func (_c *MockBookingServiceServer_GetBackupQuote_Call) Run(run func(context1 context.Context, getBackupQuoteRequest *bookingv1.GetBackupQuoteRequest)) *MockBookingServiceServer_GetBackupQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.GetBackupQuoteRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.GetBackupQuoteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_GetBackupQuote_Call) Return(getBackupQuoteResponse *bookingv1.GetBackupQuoteResponse, err error) *MockBookingServiceServer_GetBackupQuote_Call {
	_c.Call.Return(getBackupQuoteResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_GetBackupQuote_Call) RunAndReturn(run func(context1 context.Context, getBackupQuoteRequest *bookingv1.GetBackupQuoteRequest) (*bookingv1.GetBackupQuoteResponse, error)) *MockBookingServiceServer_GetBackupQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackage provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) GetPackage(context1 context.Context, getPackageRequest *bookingv1.GetPackageRequest) (*bookingv1.GetPackageResponse, error) {
	ret := _mock.Called(context1, getPackageRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetPackage")
	}

	var r0 *bookingv1.GetPackageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.GetPackageRequest) (*bookingv1.GetPackageResponse, error)); ok {
		return returnFunc(context1, getPackageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.GetPackageRequest) *bookingv1.GetPackageResponse); ok {
		r0 = returnFunc(context1, getPackageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.GetPackageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.GetPackageRequest) error); ok {
		r1 = returnFunc(context1, getPackageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_GetPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackage'
type MockBookingServiceServer_GetPackage_Call struct {
	*mock.Call
}

// GetPackage is a helper method to define mock.On call
//   - context1 context.Context
//   - getPackageRequest *bookingv1.GetPackageRequest
func (_e *MockBookingServiceServer_Expecter) GetPackage(context1 interface{}, getPackageRequest interface{}) *MockBookingServiceServer_GetPackage_Call {
	return &MockBookingServiceServer_GetPackage_Call{Call: _e.mock.On("GetPackage", context1, getPackageRequest)}
}

func (_c *MockBookingServiceServer_GetPackage_Call) Run(run func(context1 context.Context, getPackageRequest *bookingv1.GetPackageRequest)) *MockBookingServiceServer_GetPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.GetPackageRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.GetPackageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_GetPackage_Call) Return(getPackageResponse *bookingv1.GetPackageResponse, err error) *MockBookingServiceServer_GetPackage_Call {
	_c.Call.Return(getPackageResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_GetPackage_Call) RunAndReturn(run func(context1 context.Context, getPackageRequest *bookingv1.GetPackageRequest) (*bookingv1.GetPackageResponse, error)) *MockBookingServiceServer_GetPackage_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) GetQuote(context1 context.Context, getQuoteRequest *bookingv1.GetQuoteRequest) (*bookingv1.GetQuoteResponse, error) {
	ret := _mock.Called(context1, getQuoteRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *bookingv1.GetQuoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.GetQuoteRequest) (*bookingv1.GetQuoteResponse, error)); ok {
		return returnFunc(context1, getQuoteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.GetQuoteRequest) *bookingv1.GetQuoteResponse); ok {
		r0 = returnFunc(context1, getQuoteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.GetQuoteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.GetQuoteRequest) error); ok {
		r1 = returnFunc(context1, getQuoteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockBookingServiceServer_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - context1 context.Context
//   - getQuoteRequest *bookingv1.GetQuoteRequest
func (_e *MockBookingServiceServer_Expecter) GetQuote(context1 interface{}, getQuoteRequest interface{}) *MockBookingServiceServer_GetQuote_Call {
	return &MockBookingServiceServer_GetQuote_Call{Call: _e.mock.On("GetQuote", context1, getQuoteRequest)}
}

func (_c *MockBookingServiceServer_GetQuote_Call) Run(run func(context1 context.Context, getQuoteRequest *bookingv1.GetQuoteRequest)) *MockBookingServiceServer_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.GetQuoteRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.GetQuoteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_GetQuote_Call) Return(getQuoteResponse *bookingv1.GetQuoteResponse, err error) *MockBookingServiceServer_GetQuote_Call {
	_c.Call.Return(getQuoteResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_GetQuote_Call) RunAndReturn(run func(context1 context.Context, getQuoteRequest *bookingv1.GetQuoteRequest) (*bookingv1.GetQuoteResponse, error)) *MockBookingServiceServer_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// ListGlobalPackages provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) ListGlobalPackages(context1 context.Context, listGlobalPackagesRequest *bookingv1.ListGlobalPackagesRequest) (*bookingv1.ListGlobalPackagesResponse, error) {
	ret := _mock.Called(context1, listGlobalPackagesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListGlobalPackages")
	}

	var r0 *bookingv1.ListGlobalPackagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListGlobalPackagesRequest) (*bookingv1.ListGlobalPackagesResponse, error)); ok {
		return returnFunc(context1, listGlobalPackagesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListGlobalPackagesRequest) *bookingv1.ListGlobalPackagesResponse); ok {
		r0 = returnFunc(context1, listGlobalPackagesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.ListGlobalPackagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.ListGlobalPackagesRequest) error); ok {
		r1 = returnFunc(context1, listGlobalPackagesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_ListGlobalPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGlobalPackages'
type MockBookingServiceServer_ListGlobalPackages_Call struct {
	*mock.Call
}

// ListGlobalPackages is a helper method to define mock.On call
//   - context1 context.Context
//   - listGlobalPackagesRequest *bookingv1.ListGlobalPackagesRequest
func (_e *MockBookingServiceServer_Expecter) ListGlobalPackages(context1 interface{}, listGlobalPackagesRequest interface{}) *MockBookingServiceServer_ListGlobalPackages_Call {
	return &MockBookingServiceServer_ListGlobalPackages_Call{Call: _e.mock.On("ListGlobalPackages", context1, listGlobalPackagesRequest)}
}

func (_c *MockBookingServiceServer_ListGlobalPackages_Call) Run(run func(context1 context.Context, listGlobalPackagesRequest *bookingv1.ListGlobalPackagesRequest)) *MockBookingServiceServer_ListGlobalPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.ListGlobalPackagesRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.ListGlobalPackagesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_ListGlobalPackages_Call) Return(listGlobalPackagesResponse *bookingv1.ListGlobalPackagesResponse, err error) *MockBookingServiceServer_ListGlobalPackages_Call {
	_c.Call.Return(listGlobalPackagesResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_ListGlobalPackages_Call) RunAndReturn(run func(context1 context.Context, listGlobalPackagesRequest *bookingv1.ListGlobalPackagesRequest) (*bookingv1.ListGlobalPackagesResponse, error)) *MockBookingServiceServer_ListGlobalPackages_Call {
	_c.Call.Return(run)
	return _c
}

// ListInferenceModels provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) ListInferenceModels(context1 context.Context, listInferenceModelsRequest *bookingv1.ListInferenceModelsRequest) (*bookingv1.ListInferenceModelsResponse, error) {
	ret := _mock.Called(context1, listInferenceModelsRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListInferenceModels")
	}

	var r0 *bookingv1.ListInferenceModelsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListInferenceModelsRequest) (*bookingv1.ListInferenceModelsResponse, error)); ok {
		return returnFunc(context1, listInferenceModelsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListInferenceModelsRequest) *bookingv1.ListInferenceModelsResponse); ok {
		r0 = returnFunc(context1, listInferenceModelsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.ListInferenceModelsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.ListInferenceModelsRequest) error); ok {
		r1 = returnFunc(context1, listInferenceModelsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_ListInferenceModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInferenceModels'
type MockBookingServiceServer_ListInferenceModels_Call struct {
	*mock.Call
}

// ListInferenceModels is a helper method to define mock.On call
//   - context1 context.Context
//   - listInferenceModelsRequest *bookingv1.ListInferenceModelsRequest
func (_e *MockBookingServiceServer_Expecter) ListInferenceModels(context1 interface{}, listInferenceModelsRequest interface{}) *MockBookingServiceServer_ListInferenceModels_Call {
	return &MockBookingServiceServer_ListInferenceModels_Call{Call: _e.mock.On("ListInferenceModels", context1, listInferenceModelsRequest)}
}

func (_c *MockBookingServiceServer_ListInferenceModels_Call) Run(run func(context1 context.Context, listInferenceModelsRequest *bookingv1.ListInferenceModelsRequest)) *MockBookingServiceServer_ListInferenceModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.ListInferenceModelsRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.ListInferenceModelsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_ListInferenceModels_Call) Return(listInferenceModelsResponse *bookingv1.ListInferenceModelsResponse, err error) *MockBookingServiceServer_ListInferenceModels_Call {
	_c.Call.Return(listInferenceModelsResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_ListInferenceModels_Call) RunAndReturn(run func(context1 context.Context, listInferenceModelsRequest *bookingv1.ListInferenceModelsRequest) (*bookingv1.ListInferenceModelsResponse, error)) *MockBookingServiceServer_ListInferenceModels_Call {
	_c.Call.Return(run)
	return _c
}

// ListPackages provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) ListPackages(context1 context.Context, listPackagesRequest *bookingv1.ListPackagesRequest) (*bookingv1.ListPackagesResponse, error) {
	ret := _mock.Called(context1, listPackagesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListPackages")
	}

	var r0 *bookingv1.ListPackagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListPackagesRequest) (*bookingv1.ListPackagesResponse, error)); ok {
		return returnFunc(context1, listPackagesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListPackagesRequest) *bookingv1.ListPackagesResponse); ok {
		r0 = returnFunc(context1, listPackagesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.ListPackagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.ListPackagesRequest) error); ok {
		r1 = returnFunc(context1, listPackagesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_ListPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPackages'
type MockBookingServiceServer_ListPackages_Call struct {
	*mock.Call
}

// ListPackages is a helper method to define mock.On call
//   - context1 context.Context
//   - listPackagesRequest *bookingv1.ListPackagesRequest
func (_e *MockBookingServiceServer_Expecter) ListPackages(context1 interface{}, listPackagesRequest interface{}) *MockBookingServiceServer_ListPackages_Call {
	return &MockBookingServiceServer_ListPackages_Call{Call: _e.mock.On("ListPackages", context1, listPackagesRequest)}
}

func (_c *MockBookingServiceServer_ListPackages_Call) Run(run func(context1 context.Context, listPackagesRequest *bookingv1.ListPackagesRequest)) *MockBookingServiceServer_ListPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.ListPackagesRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.ListPackagesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_ListPackages_Call) Return(listPackagesResponse *bookingv1.ListPackagesResponse, err error) *MockBookingServiceServer_ListPackages_Call {
	_c.Call.Return(listPackagesResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_ListPackages_Call) RunAndReturn(run func(context1 context.Context, listPackagesRequest *bookingv1.ListPackagesRequest) (*bookingv1.ListPackagesResponse, error)) *MockBookingServiceServer_ListPackages_Call {
	_c.Call.Return(run)
	return _c
}

// ListStorageTierTypes provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) ListStorageTierTypes(context1 context.Context, listStorageTierTypesRequest *bookingv1.ListStorageTierTypesRequest) (*bookingv1.ListStorageTierTypesResponse, error) {
	ret := _mock.Called(context1, listStorageTierTypesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListStorageTierTypes")
	}

	var r0 *bookingv1.ListStorageTierTypesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListStorageTierTypesRequest) (*bookingv1.ListStorageTierTypesResponse, error)); ok {
		return returnFunc(context1, listStorageTierTypesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bookingv1.ListStorageTierTypesRequest) *bookingv1.ListStorageTierTypesResponse); ok {
		r0 = returnFunc(context1, listStorageTierTypesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingv1.ListStorageTierTypesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bookingv1.ListStorageTierTypesRequest) error); ok {
		r1 = returnFunc(context1, listStorageTierTypesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingServiceServer_ListStorageTierTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStorageTierTypes'
type MockBookingServiceServer_ListStorageTierTypes_Call struct {
	*mock.Call
}

// ListStorageTierTypes is a helper method to define mock.On call
//   - context1 context.Context
//   - listStorageTierTypesRequest *bookingv1.ListStorageTierTypesRequest
func (_e *MockBookingServiceServer_Expecter) ListStorageTierTypes(context1 interface{}, listStorageTierTypesRequest interface{}) *MockBookingServiceServer_ListStorageTierTypes_Call {
	return &MockBookingServiceServer_ListStorageTierTypes_Call{Call: _e.mock.On("ListStorageTierTypes", context1, listStorageTierTypesRequest)}
}

func (_c *MockBookingServiceServer_ListStorageTierTypes_Call) Run(run func(context1 context.Context, listStorageTierTypesRequest *bookingv1.ListStorageTierTypesRequest)) *MockBookingServiceServer_ListStorageTierTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bookingv1.ListStorageTierTypesRequest
		if args[1] != nil {
			arg1 = args[1].(*bookingv1.ListStorageTierTypesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingServiceServer_ListStorageTierTypes_Call) Return(listStorageTierTypesResponse *bookingv1.ListStorageTierTypesResponse, err error) *MockBookingServiceServer_ListStorageTierTypes_Call {
	_c.Call.Return(listStorageTierTypesResponse, err)
	return _c
}

func (_c *MockBookingServiceServer_ListStorageTierTypes_Call) RunAndReturn(run func(context1 context.Context, listStorageTierTypesRequest *bookingv1.ListStorageTierTypesRequest) (*bookingv1.ListStorageTierTypesResponse, error)) *MockBookingServiceServer_ListStorageTierTypes_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedBookingServiceServer provides a mock function for the type MockBookingServiceServer
func (_mock *MockBookingServiceServer) mustEmbedUnimplementedBookingServiceServer() {
	_mock.Called()
	return
}

// MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedBookingServiceServer'
type MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedBookingServiceServer is a helper method to define mock.On call
func (_e *MockBookingServiceServer_Expecter) mustEmbedUnimplementedBookingServiceServer() *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call {
	return &MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedBookingServiceServer")}
}

func (_c *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call) Run(run func()) *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call) Return() *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call) RunAndReturn(run func()) *MockBookingServiceServer_mustEmbedUnimplementedBookingServiceServer_Call {
	_c.Run(run)
	return _c
}
