name: Build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  GOTOOLCHAIN: local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up tools
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          version: 2026.3.8

      - name: Run GoReleaser
        run: goreleaser release --clean --snapshot

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: Preview Binaries
          path: dist/qcloud_*/qcloud*

